### ISSUE TITLE
Zalenium hub probes failure

### ISSUE THREAD

**Issue by baflQA** [zalando/zalenium#1001]
## 🐛 Bug Report

From time to time, the zalenium hub is restarted due to the probes failures. 
The console page cannot be reached. 

Our assumption is, that somewhere there, some proxy, or all the proxies, cannot be reached: 
https://github.com/zalando/zalenium/blob/fc6f18a44e3e772fbbfadc188a1583d3d2fbee38/src/main/java/de/zalando/ep/zalenium/servlet/ZaleniumConsoleServlet.java#L67-L69

A minutes before the hub restart, We've noticed that some test has crashed with the 
> Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure

exception. 

We assume that in case of some problems with one of the nodes, the hub might be restarted due to the problems with getting the proxy (proxies?) when creating a console page. 
The interesting part is, that the zalenium dashboard was still available, and all the tests proceeded. 

In the logs of the restarted hub We have found:
`15:47:54.533 [Thread-89999] WARN  d.z.e.z.proxy.AutoStartProxySet - Registered (or re-registered) a container zalenium-zalenium-hub-40000-hqplm http://100.120.21.127:40000 that is not tracked by the pool, marking down.
	at de.zalando.ep.zalenium.proxy.DockerSeleniumRemoteProxy.<init>(DockerSeleniumRemoteProxy.java:110)
	at de.zalando.ep.zalenium.proxy.DockerSeleniumRemoteProxy.<init>(DockerSeleniumRemoteProxy.java:110)
15:48:58.571 [Thread-90138] WARN  d.z.e.z.proxy.AutoStartProxySet - Registered (or re-registered) a container zalenium-zalenium-hub-40000-hqplm http://100.120.21.127:40000 that is not tracked by the pool, marking down.
15:50:02.608 [Thread-90292] WARN  d.z.e.z.proxy.AutoStartProxySet - Registered (or re-registered) a container zalenium-zalenium-hub-40000-hqplm http://100.120.21.127:40000 that is not tracked by the pool, marking down.
15:51:06.636 [Thread-90445] WARN  d.z.e.z.proxy.AutoStartProxySet - Registered (or re-registered) a container zalenium-zalenium-hub-40000-hqplm http://100.120.21.127:40000 that is not tracked by the pool, marking down.
15:52:10.682 [Thread-90536] WARN  d.z.e.z.proxy.AutoStartProxySet - Registered (or re-registered) a container zalenium-zalenium-hub-40000-hqplm http://100.120.21.127:40000 that is not tracked by the pool, marking down.
15:53:14.726 [Thread-90624] WARN  d.z.e.z.proxy.AutoStartProxySet - Registered (or re-registered) a container zalenium-zalenium-hub-40000-hqplm http://100.120.21.127:40000 that is not tracked by the pool, marking down.
15:54:03.161 [Thread-90677] WARN  d.z.e.z.proxy.AutoStartProxySet - Registered (or re-registered) a container zalenium-zalenium-hub-40000-79mxv http://100.104.37.161:40000 that is shutting down, marking down.
15:54:18.755 [Thread-90688] WARN  d.z.e.z.proxy.AutoStartProxySet - Registered (or re-registered) a container zalenium-zalenium-hub-40000-hqplm http://100.120.21.127:40000 that is not tracked by the pool, marking down.
15:55:05.524 [Thread-90711] INFO  d.z.e.z.proxy.SessionRequestFilter - Request has waited 30 attempts for a node, something went wrong with the previous attempts, creating a new node for {zal:idleTimeout=150, credentials_enable_service=false, goog:chromeOptions={args=[--no-sandbox, --disable-dev-shm-usage, disable-infobars, --headless, --disable-gpu, --window-size=1440x900], extensions=[]}, zal:recordVideo=false, loggingPrefs=org.openqa.selenium.logging.LoggingPreferences@8ff28c0, browserName=chrome, profile.password_manager_enabled=false, zal:name=someTest, zal:build=someBuild}.
15:55:22.784 [Thread-90733] WARN  d.z.e.z.proxy.AutoStartProxySet - Registered (or re-registered) a container zalenium-zalenium-hub-40000-hqplm http://100.120.21.127:40000 that is not tracked by the pool, marking down.
15:56:26.809 [Thread-90807] WARN  d.z.e.z.proxy.AutoStartProxySet - Registered (or re-registered) a container zalenium-zalenium-hub-40000-hqplm http://100.120.21.127:40000 that is not tracked by the pool, marking down.
15:57:30.840 [Thread-90884] WARN  d.z.e.z.proxy.AutoStartProxySet - Registered (or re-registered) a container zalenium-zalenium-hub-40000-hqplm http://100.120.21.127:40000 that is not tracked by the pool, marking down.
15:58:34.881 [Thread-90927] WARN  d.z.e.z.proxy.AutoStartProxySet - Registered (or re-registered) a container zalenium-zalenium-hub-40000-hqplm http://100.120.21.127:40000 that is not tracked by the pool, marking down.`

## To Reproduce
Start 30-40 new chrome sessions, expect some of them to fail due to the 
> Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure

error, expect hub pod to be restarted. 

## Expected behavior

Hub pod is working even if the node pod has crashed. 

## Environment
K8S
Zalenium Image Version(s): 3.141.59m hub, elgalu/selenium:3.14.0-p23 nodes
Deployed with given values.yaml:
```
hub:
  serviceAnnotations:
    "external-dns.alpha.kubernetes.io/hostname": someHost.io.
    service.beta.kubernetes.io/aws-load-balancer-internal: "0.0.0.0/0"
    service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "1200"
    prometheus.io/scrape: "true"

  ## The repository and image
  ## ref: https://hub.docker.com/r/selenium/hub/
  image: "dosel/zalenium"

  ## The tag for the image
  ## ref: https://hub.docker.com/r/selenium/hub/tags/
  tag: "3.141.59m"

  ## Specify a imagePullPolicy
  ## ref: http://kubernetes.io/docs/user-guide/images/#pre-pulling-images
  pullPolicy: "IfNotPresent"

  ## The port which the hub listens on
  port: 4444

  ## Timeout for probe Hub readiness via HTTP request on Hub console
  readinessTimeout: 300
  ## Timeout for probe Hub liveness via HTTP request on Hub console
  livenessTimeout: 300
  ## Intial Delay for probe Hub liveness via HTTP request on Hub console
  livenessInitialDelay: 600

  ## Set the JAVA_OPTS environment variable
  ## If you find your selenium hub is OOMKilled, try adding -XX:+UseSerialGC
  javaOpts: "-Xmx400m -XX:+UseSerialGC"

  ## Set the SE_OPTS environment variable
  ## ref: http://www.seleniumhq.org/docs/07_selenium_grid.jsp#node-configuration
  # seOpts:

  ## Defining a JMX port will open the port on the container, however, it
  ## requires additional javaOpts, ie
  ## javaOpts: >
  ##   -Dcom.sun.management.jmxremote.port=4000
  ##   -Dcom.sun.management.jmxremote.authenticate=false
  ##   -Dcom.sun.management.jmxremote.ssl=false
  ## ref: http://openjdk.java.net/groups/jmx/
  # jmxPort: 4000

  ## Use persistent storage or local?
  persistentVolumesEnabled: true
  localVolumesRoot: '/tmp'

  ## Configure resource requests and limits
  ## ref: http://kubernetes.io/docs/user-guide/compute-resources/
  resources:
    limits:
      cpu: "1"
      memory: "3Gi"
    requests:
      cpu: "0.7"
      memory: "2Gi"

  ## The type of service to create
  ##   Values: ClusterIP, NodePort, LoadBalancer, or ExternalName
  ## ref: https://kubernetes.io/docs/user-guide/services/
  serviceType: "LoadBalancer"

  ## Control where client requests go, to the same pod or round-robin
  ##   Values: ClientIP or None
  ## ref: https://kubernetes.io/docs/user-guide/services/
  serviceSessionAffinity: "None"

  # Zalenium hub uses these values to schedule pods through the k8s apiserver.
  cpuRequest: 500m
  cpuLimit: 1000m
  memRequest: 700Mi
  memLimit: 1Gi

  ## Start arguments for Zalenium hub itself
  ## https://github.com/zalando/zalenium/blob/master/docs/usage_examples.md
  desiredContainers: 1
  maxDockerSeleniumContainers: 60
  sauceLabsEnabled: false
  browserStackEnabled: false
  testingBotEnabled: false
  videoRecordingEnabled: false
  screenWidth: 1440
  screenHeight: 900
  timeZone: "Europe/Berlin"
  seleniumImageName: "elgalu/selenium:3.14.0-p23"
  maxTestSessions: 1
  debugEnabled: false
  sendAnonymousUsageInfo: false
  keepOnlyFailedTests: true
  retentionPeriod: 2

  # Environment variables passed to Zalenium hub.
  sauceUserName: blank
  sauceAccessKey: blank
  browserStackUser: blank
  browserStackKey: blank
  testingBotKey: blank
  testingBotSecret: blank
  # Allow selenium pods to be scheduled on nodes based on labels (comma-separated string env variable in deployment.yaml)
  nodeSelector: ""
  # Allow selenium pods to be scheduled on nodes with taints (will translate to a string env variable in deploment.yaml)
  tolerations: ""

  podLabels:
    maintainer_team: "infrastructure"

## Allow hub pod to be scheduled on nodes based on labels
nodeSelector: {}

## Allow hub pod to be scheduled on nodes with taints
tolerations: []
```

I know that this issue lacks details, but that's all I've got for now. I would be grateful If someone has some ideas on how to dig into the root cause of the restarts.
