### ISSUE TITLE
Could not evaluate XPath: "//*[@id='navbar']/div/div/div[2]/nav/ul/li[2]/a" (InvalidArgumentException)

### ISSUE THREAD

**Issue by kamal2222ahmed** [zalando/zalenium#1022]
## 🐛 Bug Report

When I Run Behat tests against zalenium, to test https://www.targetsite.com, all tests fail with error similar to:

 
## To Reproduce
Dockerfile ( in the same directory as docker-compose.yml )
```
FROM docksal/behat:latest
COPY ./test-suite /src
RUN mkdir /data/
RUN cd /src \
    composer install --dev --prefer-dist \
    composer update
EXPOSE 8000
ENTRYPOINT ["php"]
CMD ["-S", "0.0.0.0:8000"]
```
I build it using ```docker run --rm  -v $(pwd):/src docksal/behat  --version```
and:
docker-compose.yml
```
version: "2"
services:
  hub:
    image: elgalu/selenium

  zalenium:
    image: "dosel/zalenium"
    container_name: zalenium
    hostname: zalenium
    tty: true
    volumes:
      - /tmp/videos:/home/seluser/videos
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev/shm:/dev/shm
    privileged: true
    environment:
      - PULL_SELENIUM_IMAGE=true
    ports:
      - 4444:4444
    command: >
      start --desiredContainers 2
            --maxDockerSeleniumContainers 4
            --maxTestSessions 4
            --screenWidth 800 --screenHeight 600
            --timeZone "America/New_York"
            --videoRecordingEnabled false
            --sauceLabsEnabled false
            --browserStackEnabled false
            --testingBotEnabled false
            --cbtEnabled false
            --startTunnel false
    extra_hosts:
      - "www.targethost.com:127.0.0.1"
  # Behat
  behat:
    hostname: behat
    image: docksal/behat
    build: .
      #extra_hosts:
      #  - "52.224.105.154:www.targethost.com"
    volumes:
      - .:/src
    # Run a built-in web server for access to HTML reports
    ports:
     - 8000:8000
    entrypoint: "php -S 0.0.0.0:8000"
```
now, behat.yml ( portion related to zalenium )
```
browser_name: chrome
      selenium2:
        wd_host: http://zalenium:4444/wd/hub
        capabilities: { "browser": "chrome", "version": "*","extra_capabilities":{"chromeOptions":{"w3c":false}}}
.............
elkan\BehatFormatter\BehatFormatterExtension:
      projectName: DOL Frontend Automation
      name: html
      renderer: Twig
      file_name: Index
      print_args: true
      print_outp: true
      loop_break: true
      show_tags: true
docker:
  extensions:
    Behat\MinkExtension:
      goutte: ~
      selenium2: ~
```
then, I run $docker-compose up -d against the docker-compose.yml file

result:
```
 $ docker-compose ps
            Name                           Command               State                Ports
---------------------------------------------------------------------------------------------------------
docksal-behat-example_behat_1   php -S 0.0.0.0:8000              Up      0.0.0.0:8000->8000/tcp
docksal-behat-example_hub_1     entry.sh                         Up
zalenium                        entry.sh start --desiredCo ...   Up      0.0.0.0:4444->4444/tcp, 4445/tcp
```
http://localhost:4444/grid/admin/live displays vnc ,a nd when I run the behat test, I see the test running on the live console.

## Expected behavior

behat test should run, when I issue the command:
./run-behat --suite=desktop --tags="englishGL && subNavGL"
which basically runs one test

Actual Result:

I get stderr:

Could not evaluate XPath: "//*[@id='navbar']/div/div/div[2]/nav/ul/li[2]/a" (InvalidArgumentException)

Could not evaluate XPath: "//*[@id='navbar']/div/div/div[2]/nav/ul/li[3]/a" (InvalidArgumentException)

Could not evaluate XPath: "//*[@id='navbar']/div/div/div[2]/nav/ul/li[4]/a" (InvalidArgumentException) 
......
## Environment

OS: OSX 10.14.5
Zalenium Image Version(s): latest
Docker version: 2.0.0.3
Docker-Compose version (if applicable): docker-compose version 1.23.2, build 1110ad01
Exact Docker command to start the containers (if using docker-compose, provide 
the docker-compose file as well):

file: run-behat
```
docker exec $(docker-compose ps -q behat) behat --colors --format=pretty --out=std --format=junit --out=$HOME/behat_report --format=html --out=build "$@"
```
docker ps:
```
CONTAINER ID        IMAGE                    COMMAND                  CREATED             STATUS              PORTS                              NAMES
2e79d7565d8d        elgalu/selenium:latest   "entry.sh"               6 minutes ago       Up 6 minutes        40001/tcp, 50001/tcp               zalenium_VZNfl2
37e37476e5ca        elgalu/selenium:latest   "entry.sh"               6 minutes ago       Up 6 minutes        40000/tcp, 50000/tcp               zalenium_qtJlb3
cec691e18e40        dosel/zalenium           "entry.sh start --de…"   6 minutes ago       Up 6 minutes        0.0.0.0:4444->4444/tcp, 4445/tcp   zalenium
313ca0538b19        elgalu/selenium          "entry.sh"               6 minutes ago       Up 6 minutes                                           docksal-behat-example_hub_1
```
if I login to elgalu/selenium container

ps -ef shows:
```
ps -ef
UID        PID  PPID  C STIME TTY          TIME CMD
seluser      1     0  0 18:23 ?        00:00:00 bash /usr/bin/run-supervisord.sh
root        14     1  0 18:23 ?        00:00:00 haveged
seluser     32     1  0 18:23 ?        00:00:00 /usr/bin/dbus-daemon --system
seluser     48     1  0 18:23 ?        00:00:00 /usr/bin/dbus-daemon --fork --print-pid 4 --print-address 6 --session
seluser    112     1  0 18:23 ?        00:00:00 Xvfb :55 -screen 0 1900x1880x24+32 -nolisten tcp -nolisten inet6 -ac -r -cc 4 -accessx -xinerama +extension Composite +extension RANDR +extension GLX
seluser    163     1  0 18:23 ?        00:00:00 /usr/bin/python3 /usr/local/bin/supervisord -c /etc/supervisor/supervisord.conf --nodaemon
seluser    166   163  0 18:23 ?        00:00:00 bash /usr/bin/start-xmanager.sh
seluser    167   163  0 18:23 ?        00:00:00 bash /usr/bin/start-vnc.sh
seluser    168   163  0 18:23 ?        00:00:00 bash /usr/bin/start-selenium-hub.sh
seluser    169   163  0 18:23 ?        00:00:00 bash /usr/bin/start-selenium-node-chrome.sh
seluser    170   166  0 18:23 ?        00:00:00 fluxbox -display :55.0 -verbose
seluser    172   163  0 18:23 ?        00:00:00 bash /usr/bin/start-selenium-node-firefox.sh
seluser    177   163  0 18:23 ?        00:00:00 bash /usr/bin/start-xterm.sh
seluser    195   168  1 18:23 ?        00:00:05 java -Xmx1637168k -jar /home/seluser/selenium-server-standalone-3.jar -port 24444 -role hub -maxSession 1 -timeout 19000 -browserTimeout 16000 -cleanUpCycle 5000
seluser    212   167  0 18:23 ?        00:00:00 x11vnc -forever -shared -rfbport 25900 -rfbportv6 25900 -display :55 -auth /var/run/slim.auth
seluser    504   172  0 18:23 ?        00:00:03 java -Dwebdriver.firefox.logfile=/var/log/cont/firefox_driver.log -Xmx1637168k -Dwebdriver.gecko.driver=/usr/bin/geckodriver -jar /home/seluser/selenium-server-standalone-
seluser    505   169  0 18:23 ?        00:00:04 java -Dwebdriver.chrome.driver=/home/seluser/chromedriver -Dwebdriver.chrome.logfile=/var/log/cont/chrome_driver.log -Dwebdriver.chrome.verboseLogging=true -Xmx1637168k -j
```
and content of /etc/hosts:

```
$ cat /etc/hosts
127.0.0.1	localhost
::1	localhost ip6-localhost ip6-loopback
fe00::0	ip6-localnet
ff00::0	ip6-mcastprefix
ff02::1	ip6-allnodes
ff02::2	ip6-allrouters
172.23.0.3	313ca0538b19
10.0.2.2   my_internal_web_server.local
172.23.0.1  docker.host
172.23.0.1  docker.host.dev
172.23.0.1  d.host.loc.dev
172.23.0.1  host.docker.local
172.23.0.1  host.docker
172.23.0.3    docker.guest
172.23.0.3    docker.guest.dev
172.23.0.3    guest.docker.local
172.23.0.3    d.guest.loc.dev
172.23.0.3    guest.docker
```
I have looked at the screenshots that were saved for all tests, and they display a browser:
```
This site Can't be reached 
www.targethost.com refused to connect
```

I added the following in docker-compose.yml

```
extra_hosts:
      - "www.targethost.com:22.123.123.123"
```
and now I get error:

```
 Webdriver http error: 400, payload :{"value":{"error":"invalid argument","message":"invalid argument: missing command parameters","stacktrace":"#0 0x564c29900299 \u003Cunknown>\n"}} (WebDriver\Exception\CurlExec)
```

So, Looking at https://medium.com/@alex.designworks/chromedriver-75-enforces-w3c-standard-breaking-behat-tests-460cad435545 how do we use selenium/standalone-chrome:3.141.59-oxygen” image.? in the zalenium setup.
