### ISSUE TITLE
Failing to load images when launched from Ingress subpath

### ISSUE THREAD

**Issue by SydoxX** [zalando/zalenium#1036]
## 🐛 Bug Report

In the grid console, images won't be loaded because the css tries to load them from the root path (/) instead of the subpath (e.g. /zalenium/)

## To Reproduce
Deploy Zalenium with an Ingress and use a subpath.

Using helm chart to deploy on Kubernetes
values.yaml
``` yaml
ingress:
  enabled: true
  tls: true
  secretName: tls-cert
  hostname: example.com
  path: /zalenium
  annotations:
    kubernetes.io/ingress.class: "traefik"
```
![image](https://user-images.githubusercontent.com/6787349/63572082-3f4de280-c582-11e9-905e-1e3825dab8d4.png)

## Expected behavior
![image](https://raw.githubusercontent.com/elgalu/docker-selenium/master/images/grid3_console.png)
## Environment

OS: 
* Browser: Firefox 68.0.2 on Windows 10
* Cluster: Debian 9.8
Zalenium Image Version(s): 3.141.59t
Docker version: 19.03.1
Kubernetes version: 1.15
Exact Docker command to start the containers (if using docker-compose, provide 
the docker-compose file as well): `helm install --name zalenium --namespace zalenium -f zalenium-values.yaml zalenium-github/zalenium`
