### ISSUE TITLE
affinity rules not applied to selenium working node pods

### ISSUE THREAD

**Issue by jkirkham-ratehub** [zalando/zalenium#1046]
## 🐛 Bug Report

Defining affinity and anti-affinity rules don't seem to apply to the selenium worker (node) pods, but only to the Zalenium Hub pod.

## To Reproduce

Affinity settings are added to the helm values.yaml file:
```
affinity:
  nodeAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 100
      preference:
        matchExpressions:
        - key: cloud.google.com/gke-nodepool
          operator: In
          values:
          - n1-std-2
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
    - labelSelector:
        matchExpressions:
        - key: app
          operator: In
          values:
          - zalenium
      topologyKey: "kubernetes.io/hostname"
```
## Expected behavior

Expected affinty rules to apply to both the hub pod and all selenium worker (node) pods, or have a separate setting for the worker pods.

## Actual behaviour

Viewing pod details with:
   `kubectl get pods <podname> -n <namespace> -o yaml`
Only the Zalenium hub YAML has the defined affinity rules but not the selenium worker node pods.
The worker node pods tends to all get provisioned on the same kubernetes cluster node, and when jobs start their memory and cpu usage rise and significantly affect performance of all selenium jobs.

## Environment

Platform: GKE kubernetes v1.13.7-gke.24
Helm version: v2.14.3
Zalenium Chart:
```
NAME                            CHART VERSION   APP VERSION     DESCRIPTION            
zalenium-github/zalenium        3.141.59        3.141.59        Chart for selenium grid
```
