### ISSUE TITLE
SauceLabsRemoteProxy failed to start after 40 seconds, failing

### ISSUE THREAD

**Issue by karl0ss** [zalando/zalenium#1070]
## 🐛 Bug Report

Unable to connect to saucelabs with the error "SauceLabsRemoteProxy failed to start after 40 seconds, failing" displayed

## To Reproduce

Running a docker-compose file that contains 

 ```
 zalenium:
    image: "dosel/zalenium"
    container_name: zalenium
    hostname: zalenium
    depends_on:
      - hub
    tty: true
    volumes:
      - /tmp/videos:/home/seluser/videos
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 4444:4444
      - 8000:8000
    command: >
      start --desiredContainers 2
            --maxDockerSeleniumContainers 8
            --screenWidth 800 --screenHeight 600
            --timeZone "Europe/Berlin"
            --videoRecordingEnabled true
            --sauceLabsEnabled true
            --browserStackEnabled false
            --testingBotEnabled false
            --cbtEnabled false
            --lambdaTestEnabled false
            --startTunnel false
    environment:
      - HOST_UID
      - HOST_GID
      - SAUCE_USERNAME=myUserName
      - SAUCE_ACCESS_KEY=XXXXXX-XX-XXXXX-XXXXX-XXXXXX
      - BROWSER_STACK_USER
      - BROWSER_STACK_KEY
      - TESTINGBOT_KEY
      - TESTINGBOT_SECRET
      - CBT_USERNAME
      - CBT_AUTHKEY
      - LT_USERNAME
      - LT_ACCESS_KEY
```

## Expected behavior

I believe this should activate a connection for sauceLabs for devices not supported by zalenium (Mobiles)

## Environment

OS: Ubuntu 18.04 Docker enviroment
Zalenium Image Version(s): Pulling latest image - 3.141.59u
Docker version:  18.06.1-ce
Docker-Compose version (if applicable): 2.1

## Log

```
Docker binary already present, will use that one.

Docker version 18.09.0, build 4d60db4

-- LOG 18:09:20:895618251 Ensuring docker works...

-- LOG 18:09:21:467332441 Ensuring docker-selenium is available...

haveged: haveged starting up


Copying files for Dashboard...

Starting Nginx reverse proxy...

Starting Selenium Hub...

................18:09:27.809 [main] INFO  o.o.grid.selenium.GridLauncherV3 - Selenium server version: 3.141.59, revision: unknown

..18:09:28.387 [main] INFO  o.o.grid.selenium.GridLauncherV3 - Launching Selenium Grid hub on port 4445

.........18:09:30.858 [main] INFO  d.z.e.z.c.DockerContainerClient - About to clean up any left over DockerSelenium containers created by Zalenium

.......................................18:09:44.088 [AutoStartProxyPoolPoller] INFO  d.z.e.z.proxy.AutoStartProxySet - Starting poller.

.........18:09:47.974 [main] INFO  d.z.ep.zalenium.aspect.HubAspect - Registering custom Zalenium servlets

.....18:09:50.901 [main] INFO  org.openqa.grid.web.Hub - Selenium Grid hub is up and running

18:09:50.904 [main] INFO  org.openqa.grid.web.Hub - Nodes should register to http://172.19.0.3:4445/grid/register/

18:09:50.907 [main] INFO  org.openqa.grid.web.Hub - Clients should connect to http://172.19.0.3:4445/wd/hub

Selenium Hub started!

Starting Sauce Labs node...

......................................18:10:14.485 [main] INFO  o.o.grid.selenium.GridLauncherV3 - Selenium server version: 3.141.59, revision: unknown

.......18:10:19.003 [main] INFO  o.o.grid.selenium.GridLauncherV3 - Launching a Selenium Grid node on port 30001

...................18:10:29.229 [main] INFO  global - Initialising WebDriverServlet

....18:10:31.907 [main] INFO  o.o.s.remote.server.SeleniumServer - Selenium Server is up and running on port 30001

18:10:31.915 [main] INFO  o.o.grid.selenium.GridLauncherV3 - Selenium Grid node is up and ready to register to the hub

SauceLabsRemoteProxy failed to start after 40 seconds, failing...
```
