### ISSUE TITLE
Only the first test suite finish sometimes successively on kubernetes

### ISSUE THREAD

**Issue by ahafid01** [zalando/zalenium#1079]
## 🐛 Bug Report

On kubernetes :
I run test suite java from container (in pod).
The first test suite finish sometimes successively sometimes failed, but the second test suite failed every time.
When the test success I have log  `org.openqa.selenium.remote.ProtocolHandshake createSession` but I havn't this log when failed.

## To Reproduce

I launch zalenium with 

    default parameters
or

    DESIRED_CONTAINERS : 1
    MAX_TEST_SESSIONS : 10
    other default parameters
or

    DESIRED_CONTAINERS : 1
or

    DESIRED_CONTAINERS : 2

I have always same result 

## Test script reproducing this issue (when applicable)

```
ChromeOptions capabilities = new ChromeOptions();
capabilities.setExperimentalOption("w3c", false);
capabilities.setCapability("name", VIDEO_FILE_NAME);
driver = new RemoteWebDriver(new URL(REMOTE_URL), capabilities);
```

```
FirefoxOptions capFF = new FirefoxOptions();
capFF.setCapability("name", VIDEO_FILE_NAME);
driver = new RemoteWebDriver(new URL(REMOTE_URL), capFF);
```

```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pod
  name: pod
  namespace: test-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pod
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: pod
    spec:
      serviceAccountName: test-sa
      containers:
        - image: dosel/zalenium
          imagePullPolicy: IfNotPresent
          name: pod
          securityContext:
            privileged: true
          env:
            - name: DESIRED_CONTAINERS
              value: "1"
          readinessProbe:
            httpGet:
              port: 4444
              path: /status
          ports:
            - containerPort: 4444
              hostPort: 4444
              protocol: TCP
              name: gate
          volumeMounts:
            - mountPath: /var/run/docker.sock
              name: docker-sock
            - mountPath: /home/seluser/videos
              name: video
          args:
            - start
      initContainers:
        - name: video-pvc-init
          image: busybox
          command: ["/bin/chmod","-R","777", "/home/seluser/videos"]
          volumeMounts:
            - mountPath: /home/seluser/videos
              name: video
      volumes:
        - hostPath:
            path: /var/run/docker.sock
          name: docker-sock
        - persistentVolumeClaim:
            claimName: video-pvc
          name: video
```

## Environment

OS: Ubuntu 18
Zalenium Image Version(s): latest
Kubernetes (managed): 1.15
