### ISSUE TITLE
how to add --privileged in the docker-compose.yml?

### ISSUE THREAD

**Issue by loudDD** [zalando/zalenium#1087]
## 🚀 Feature Proposal

A clear and concise description of what the feature is.

## Motivation

Please outline the motivation for the proposal.

## Example

Please provide an example for how this feature would be used.

**Comment by yosserO** [comment]
I  think you can specify it in the command entry like this:

```
version: "3.7"

services:
  zalenium:
    image: dosel/zalenium
    user: seluser:<gid> # required when running in a swarm without sudo - use the <gid> of docker group of swarm
    hostname: zalenium
    deploy:
      placement:
        constraints:
            - node.role == manager
    ports:
        - "4444:4444"
        - "8000:8000" # port for remote debugging zalenium code
    networks:
        - zalenium # attachable overlay network to use
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - /tmp/videos:/home/seluser/videos
    environment:
        - PULL_SELENIUM_IMAGE=true
        - ZALENIUM_PROXY_CLEANUP_TIMEOUT=1800
    command: ["start", "--swarmOverlayNetwork", "STACK_zalenium", "--videoRecordingEnabled", "false", "--privileged"]

networks:
    zalenium:
        driver: overlay
        attachable: true
```
