### ISSUE TITLE
UnreachableBrowserException in middle of testing

### ISSUE THREAD

**Issue by joshzcold** [zalando/zalenium#1090]
## 🐛 Bug Report

During testing we will have chrome instances launch successfully to start testing.
after a couple of tests automation has trouble launching new chrome instances.
This error will fail almost all of our test repeatally. 

Here is the error 
```
INFO: Using `new ChromeOptions()` is preferred to `DesiredCapabilities.chrome()`
org.openqa.selenium.remote.UnreachableBrowserException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.
Build info: version: '3.12.0', revision: '7c6e0b3', time: '2018-05-08T14:04:26.12Z'
System info: host: 'prvqeaa950', ip: '10.204.128.209', os.name: 'Linux', os.arch: 'amd64', os.version: '4.15.0-66-generic', java.version: '1.8.0_191'
Driver info: driver.version: RemoteWebDriver```
```
we have a 4 node k8s cluster that seems healthy 
```
prvqeaa959   Ready    master   119d    v1.15.1
vlab002304   Ready    <none>   6d18h   v1.15.3
vlab002307   Ready    <none>   23h     v1.15.3
vlab002308   Ready    <none>   23h     v1.15.3
```
```
NAME                                    READY   STATUS    RESTARTS   AGE
zal-release-zalenium-6cd9c87889-mjswn   1/1     Running   2          41h
zalenium-40000-dhggs                    1/1     Running   0          40h
zalenium-40000-vt78s                    1/1     Running   0          40h
zalenium-40000-wncbg                    1/1     Running   0          40h
zalenium-40000-xhm59                    1/1     Running   0          40h
zalenium-6494c49645-pcvdx               1/1     Running   3          42h
```

Here is an error output that might be related found in the pod logs 

```
io.fabric8.kubernetes.client.KubernetesClientException: Operation: [get]  for kind: [Pod]  with name: [zalenium-40000-dpn94]  in namespace: [default]  failed.
	at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:64)
	at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:72)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.getMandatory(BaseOperation.java:221)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.get(BaseOperation.java:177)
	at de.zalando.ep.zalenium.container.kubernetes.KubernetesContainerClient.isTerminated(KubernetesContainerClient.java:418)
	at de.zalando.ep.zalenium.proxy.DockeredSeleniumStarter.containerHasFinished(DockeredSeleniumStarter.java:350)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174)
	at java.util.concurrent.ConcurrentHashMap$KeySpliterator.forEachRemaining(ConcurrentHashMap.java:3527)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566)
	at de.zalando.ep.zalenium.proxy.AutoStartProxySet.checkContainers(AutoStartProxySet.java:353)
	at de.zalando.ep.zalenium.proxy.AutoStartProxySet.lambda$0(AutoStartProxySet.java:124)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.ConnectException: Failed to connect to /10.96.0.1:443
	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:247)
	at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:165)
	at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:257)
	at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:135)
	at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:114)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.pr
```

Here is some of the code to launch the remote web driver.
```groovy
// browser is set to chrome eariler in the code. We have found the same issue on chrome and firefox

        capabilities.setCapability(CapabilityType.UNEXPECTED_ALERT_BEHAVIOUR, UnexpectedAlertBehaviour.ACCEPT)
//        capabilities.setCapability("name", testName)
//        capabilities.setCapability("idleTimeout", 600)

            webDriver = new RemoteWebDriver(new URL("http://10.204.128.218:32222/wd/hub"), capabilities)
```
We also have a method that cleans up the driver after a test is done with it (this is supposed to be compatible with parallel testing. We have tested commenting out this method and we still get the same error)

```groovy
List currentDriver = WebDriverTracker.WEB_DRIVERS.getDrivers().get(Thread.currentThread().getId() as String)
        currentDriver.each { driver ->
            driver.quit()
        }
```

## To Reproduce

Steps to reproduce the behavior (including the docker command/docker-compose/Kubernetes manifests to start Zalenium):

*Manifest* specified at the bottom  

## Expected behavior

Successful launch of new browsers with a stable connection between them.

## Test script reproducing this issue (when applicable)

Unfortunalty I can't share the repo, but I can seek out more logs and try as many differn't scenarios as needed.

## Environment

OS: 
Zalenium Image Version(s): 
Docker version: 
```
Client:
 Version:           18.09.7
 API version:       1.39
 Go version:        go1.10.4
 Git commit:        2d0083d
 Built:             Fri Aug 16 14:19:32 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.09.7
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.4
  Git commit:       2d0083d
  Built:            Wed Aug 14 19:38:45 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```
If using Kubernetes, specify your environment, and if relevant your manifests:
zalenium deploy yaml created from helm template: 
```yaml
---
# Source: zalenium/templates/service-account.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: zal-release-zalenium
  labels:
    role: grid
    app: zalenium
    chart: zalenium-3.141.59
    release: zal-release
    heritage: Tiller
    app.kubernetes.io/name: zalenium
    helm.sh/chart: zalenium-3.141.59
    app.kubernetes.io/instance: zal-release
    app.kubernetes.io/managed-by: Tiller
---
# Source: zalenium/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: zal-release-zalenium
  labels:
    role: grid
    app: zalenium
    chart: zalenium-3.141.59
    release: zal-release
    heritage: Tiller
    app.kubernetes.io/name: zalenium
    helm.sh/chart: zalenium-3.141.59
    app.kubernetes.io/instance: zal-release
    app.kubernetes.io/managed-by: Tiller
spec:
  type: "NodePort"
  sessionAffinity: "None"
  ports:
  - name: hub
    port: 80
    targetPort: 4444
    nodePort: 32222
  selector:
    app.kubernetes.io/name: zalenium
    app.kubernetes.io/instance: zal-release

---
# Source: zalenium/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zal-release-zalenium
  labels:
    role: grid
    app: zalenium
    chart: zalenium-3.141.59
    release: zal-release
    heritage: Tiller
    app.kubernetes.io/name: zalenium
    helm.sh/chart: zalenium-3.141.59
    app.kubernetes.io/instance: zal-release
    app.kubernetes.io/managed-by: Tiller
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: zalenium
      app.kubernetes.io/instance: zal-release
  template:
    metadata:
      labels:
        role: grid
        app: zalenium
        chart: zalenium-3.141.59
        release: zal-release
        heritage: Tiller
        app.kubernetes.io/name: zalenium
        helm.sh/chart: zalenium-3.141.59
        app.kubernetes.io/instance: zal-release
        app.kubernetes.io/managed-by: Tiller
      annotations:
        {}

    spec:
      securityContext:
        {}

      volumes:
        - name: zal-release-zalenium-videos
          emptyDir: {}
        - name: zal-release-zalenium-data
          emptyDir: {}
      containers:
        - name: zalenium
          image: "dosel/zalenium:3"
          imagePullPolicy: IfNotPresent
          securityContext:
            {}

          ports:
            - containerPort: 4444
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /status
              port: 4444
            initialDelaySeconds: 90
            periodSeconds: 5
            timeoutSeconds: 1
          readinessProbe:
            httpGet:
              path: /status
              port: 4444
            timeoutSeconds: 1
          env:
            - name: ZALENIUM_KUBERNETES_CPU_REQUEST
              value: "250m"
            - name: ZALENIUM_KUBERNETES_CPU_LIMIT
              value: "1000m"
            - name: ZALENIUM_KUBERNETES_MEMORY_REQUEST
              value: "500Mi"
            - name: ZALENIUM_KUBERNETES_MEMORY_LIMIT
              value: "2Gi"
            - name: DESIRED_CONTAINERS
              value: "2"
            - name: MAX_DOCKER_SELENIUM_CONTAINERS
              value: "10"
            - name: SELENIUM_IMAGE_NAME
              value: "elgalu/selenium"
            - name: VIDEO_RECORDING_ENABLED
              value: "true"
            - name: SCREEN_WIDTH
              value: "1440"
            - name: SCREEN_HEIGHT
              value: "900"
            - name: MAX_TEST_SESSIONS
              value: "1"
            - name: NEW_SESSION_WAIT_TIMEOUT
              value: "600000"
            - name: DEBUG_ENABLED
              value: "false"
            - name: SEND_ANONYMOUS_USAGE_INFO
              value: "true"
            - name: TZ
              value: "UTC"
            - name: KEEP_ONLY_FAILED_TESTS
              value: "false"
            - name: RETENTION_PERIOD
              value: "3"
          args:
            - start
          resources:
            requests:
              cpu: 500m
              memory: 500Mi

          volumeMounts:
            - name: zal-release-zalenium-videos
              mountPath: /home/seluser/videos
            - name: zal-release-zalenium-data
              mountPath: /tmp/mounted
      serviceAccountName: zal-release-zalenium
---
# Source: zalenium/templates/role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: "Role"
metadata:
  name: zal-release-zalenium
  labels:
    role: grid
    app: zalenium
    chart: zalenium-3.141.59
    release: zal-release
    heritage: Tiller
    app.kubernetes.io/name: zalenium
    helm.sh/chart: zalenium-3.141.59
    app.kubernetes.io/instance: zal-release
    app.kubernetes.io/managed-by: Tiller
rules:
- apiGroups:
  - ""
  attributeRestrictions: null
  resources:
  - pods
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - watch
- apiGroups:
  - ""
  attributeRestrictions: null
  resources:
  - pods/exec
  verbs:
  - create
  - get
---
# Source: zalenium/templates/role-binding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: "RoleBinding"
metadata:
  name: zal-release-zalenium
  labels:
    role: grid
    app: zalenium
    chart: zalenium-3.141.59
    release: zal-release
    heritage: Tiller
    app.kubernetes.io/name: zalenium
    helm.sh/chart: zalenium-3.141.59
    app.kubernetes.io/instance: zal-release
    app.kubernetes.io/managed-by: Tiller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: "Role"
  name: zal-release-zalenium
subjects:
- kind: ServiceAccount
  name: zal-release-zalenium
---
# Source: zalenium/templates/deployment-config.yaml

---
# Source: zalenium/templates/ingress.yaml

---
# Source: zalenium/templates/pvc-data.yaml

---
# Source: zalenium/templates/pvc-video.yaml

---
# Source: zalenium/templates/route.yaml

---
# Source: zalenium/templates/secret.yaml
```
Thank you for any help, I know this issue is ambiguous, but I am willing to provide any extra help I can.
