### ISSUE TITLE
How to change the generated slave container's base name when running on OpenShift?

### ISSUE THREAD

**Issue by svenstaro** [zalando/zalenium#1123]
## 🐛 Bug Report

My containers generated on OpenShift by Zalenium work fine and I have videos and I'm actually pretty happy. However, they are called `null-40000-25t48`, `null-40000-ad12a` and such. They also don't receive proper labels. How can I change this and choose a proper base name such as `zalenium-slave`? Also, it'd be useful to choose their labels to be `app=zalenium-slave` or such.

I'm not sure this is a bug report or a feature request but it doesn't seem intended for them to be called `null-40000` as a base name.

Does this have something to do with the initiator that launches the containers? I feel they should still receive a proper name and labels.

## To Reproduce

Steps to reproduce the behavior (including the docker command/docker-compose/Kubernetes manifests to start Zalenium):

We run Zalenium on OpenShift using this template:

```yaml
---
kind: Template
apiVersion: v1
labels:
  app: zalenium
metadata:
  name: zalenium
  annotations:
    description: Zalenium service

parameters:
- description: Volume space available for videos
  displayName: Volume Capacity
  name: VOLUME_CAPACITY
  required: true
  value: 100Gi

objects:
- kind: ImageStream
  apiVersion: v1
  metadata:
    name: zalenium
  spec:
    tags:
    - from:
        kind: DockerImage
        name: docker.io/dosel/zalenium:latest
      importPolicy:
        scheduled: true
      name: latest
      referencePolicy:
        type: Source

- kind: ImageStream
  apiVersion: v1
  metadata:
    name: selenium
  spec:
    tags:
    - from:
        kind: DockerImage
        name: docker.io/elgalu/selenium:latest
      importPolicy:
        scheduled: true
      name: latest
      referencePolicy:
        type: Source

- kind: Route
  apiVersion: v1
  metadata:
    name: zalenium
  spec:
    to:
      kind: Service
      name: zalenium
    tls:
      insecureEdgeTerminationPolicy: Redirect
      termination: edge

- kind: PersistentVolumeClaim
  apiVersion: v1
  metadata:
    name: zalenium-videos
  spec:
    accessModes:
    - ReadWriteMany
    resources:
      requests:
        storage: ${VOLUME_CAPACITY}
    storageClassName: blah2

- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    name: zalenium
  spec:
    replicas: 1
    selector:
      name: zalenium
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          name: zalenium
      spec:
        containers:
        - name: zalenium
          imagePullPolicy: Always
          args:
            - "start"
            - "--desiredContainer"
            - "10"
            - "--maxDockerSeleniumContainer"
            - "100"
            - "--maxTestSessions"
            - "10"
            - "--sendAnonymousUsageInfo"
            - "false"
          env:
            - name: ZALENIUM_KUBERNETES_CPU_REQUEST
              value: 500m
            - name: ZALENIUM_KUBERNETES_CPU_LIMIT
              value: 2
            - name: ZALENIUM_KUBERNETES_MEMORY_REQUEST
              value: 1Gi
            - name: ZALENIUM_KUBERNETES_MEMORY_LIMIT
              value: 4Gi
          livenessProbe:
            failureThreshold: 2
            httpGet:
              path: /
              port: 4444
            initialDelaySeconds: 30
            periodSeconds: 60
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 4444
            initialDelaySeconds: 3
            timeoutSeconds: 10
          resources:
            requests:
              cpu: "100m"
              memory: "512M"
            limits:
              cpu: "1"
              memory: "2G"
          volumeMounts:
          - mountPath: /home/seluser/videos
            name: zalenium-videos
        serviceAccountName: zalenium
        volumes:
        - name: zalenium-videos
          persistentVolumeClaim:
            claimName: zalenium-videos
    triggers:
      - type: ConfigChange
      - imageChangeParams:
          automatic: true
          containerNames:
          - zalenium
          from:
            kind: ImageStreamTag
            name: zalenium:latest
            namespace: blah
        type: ImageChange

- kind: Service
  apiVersion: v1
  metadata:
    name: zalenium
  spec:
    selector:
      name: zalenium
    ports:
    - name: zalenium
      protocol: TCP
      port: 4444
      targetPort: 4444

- kind: RoleBinding
  apiVersion: v1
  groupNames: null
  metadata:
    name: zalenium_edit
  roleRef:
    name: edit
  subjects:
  - kind: ServiceAccount
    name: zalenium
    namespace: blah
```

## Expected behavior

I'd expect the container to be called something with `zalenium` in the name to make them easy to spot. I'd also expect them to be assigned labels so as to be able to easily select all Zalenium slaves.

## Test script reproducing this issue (when applicable)

The containers are launched from a somewhat involved build process. I will whip something up in case this part turns out to be the issue.

## Environment

OS: RHEL 7
Zalenium Image Version(s): 3.141.59w
Docker version: unknown
Docker-Compose version (if applicable): N/A
Exact Docker command to start the containers (if using docker-compose, provide 
the docker-compose file as well): N/A
If using Kubernetes, specify your environment, and if relevant your manifests: see above
