### ISSUE TITLE
hub.retentionPeriod is ignored

### ISSUE THREAD

**Issue by axozoid** [zalando/zalenium#1124]
## 🐛 Bug Report

We observe that Zalenium pod keeps growing till it's maximum memory limit and remains at that level till we manually clean up the dashboard or kill the pod.

## To Reproduce

Zalenium is deployed via the chart.

## Expected behavior

Dashboard cleanup happens automatically.

## Environment
Selenium image: elgalu/selenium:3.141.59-p27
Zalenium image: dosel/zalenium:3.141.59u

OS: 
```
uname -a
Linux ip-10-44-14-143 4.9.0-9-amd64 #1 SMP Debian 4.9.168-1+deb9u3 (2019-06-16) x86_64 GNU/Linux
```
Docker version: 
```
Server:
 Engine:
  Version:          18.06.3-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       d7080c1
  Built:            Wed Feb 20 02:26:51 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

If using Kubernetes, specify your environment, and if relevant your manifests:
`env` block from a manifest is like this:
```
         env:
          - name: ZALENIUM_KUBERNETES_CPU_REQUEST
            value: "1.5"
          - name: ZALENIUM_KUBERNETES_CPU_LIMIT
            value: "1.5"
          - name: ZALENIUM_KUBERNETES_MEMORY_REQUEST
            value: 1.5Gi
          - name: ZALENIUM_KUBERNETES_MEMORY_LIMIT
            value: 2.5Gi
          - name: DESIRED_CONTAINERS
            value: "2"
          - name: MAX_DOCKER_SELENIUM_CONTAINERS
            value: "15"
          - name: SELENIUM_IMAGE_NAME
            value: elgalu/selenium:3.141.59-p27
          - name: VIDEO_RECORDING_ENABLED
            value: "true"
          - name: SCREEN_WIDTH
            value: "1440"
          - name: SCREEN_HEIGHT
            value: "900"
          - name: MAX_TEST_SESSIONS
            value: "1"
          - name: NEW_SESSION_WAIT_TIMEOUT
            value: "600000"
          - name: DEBUG_ENABLED
            value: "true"
          - name: SEND_ANONYMOUS_USAGE_INFO
            value: "true"
          - name: TZ
            value: Australia/Sydney
          - name: KEEP_ONLY_FAILED_TESTS
            value: "false"
          - name: RETENTION_PERIOD
            value: "1"
          - name: CONTEXT_PATH
            value: /
```
and the `resource` block is like this:
```
          resources:
            limits:
              cpu: 500m
              memory: 6Gi
            requests:
              cpu: 500m
              memory: 6Gi
```

Please assist in troubleshooting why dashboard cleanup doesn't happen automatically and a pod keeps staying at the limit level.
