### ISSUE TITLE
Pods keep failing rapidly since 3.141.59x on OpenShift

### ISSUE THREAD

**Issue by svenstaro** [zalando/zalenium#1135]
## 💥 Regression Report

We get rapidly failing and restarting containers starting with 3.141.59x. This is on OpenShift 3.11 which is likely relevant. The errors observed are:

```
/usr/bin/entry.sh: line 234: /var/run/secrets/kubernetes.io/serviceaccount/da1d7f8f-a2c2-4e38-ab32-3dbc9ced86c7/var/log/cont/firefox_browser.log: No such file or directory
```
upon which the container terminates and Zalenium tries to start a new one.

## Last working version

Worked up to version: 3.141.59w

Stopped working in version: 3.141.59x

## To Reproduce

Broken config:
```
---
kind: Template
apiVersion: v1
labels:
  app: zalenium
metadata:
  name: zalenium
  annotations:
    description: Zalenium service

parameters:
- description: Volume space available for videos
  displayName: Volume Capacity
  name: VOLUME_CAPACITY
  required: true
  value: 100Gi

objects:
- kind: ImageStream
  apiVersion: v1
  metadata:
    name: zalenium
  spec:
    tags:
    - from:
        kind: DockerImage
        name: docker.io/dosel/zalenium:3.141.59x
      importPolicy:
        scheduled: true
      name: latest
      referencePolicy:
        type: Source

- kind: ImageStream
  apiVersion: v1
  metadata:
    name: selenium
  spec:
    tags:
    - from:
        kind: DockerImage
        name: docker.io/elgalu/selenium:latest
      importPolicy:
        scheduled: true
      name: latest
      referencePolicy:
        type: Source

- kind: Route
  apiVersion: v1
  metadata:
    name: zalenium
  spec:
    host: esp-zalenium.int.kn
    to:
      kind: Service
      name: zalenium
    tls:
      insecureEdgeTerminationPolicy: Redirect
      termination: edge

- kind: PersistentVolumeClaim
  apiVersion: v1
  metadata:
    name: zalenium-videos
  spec:
    accessModes:
    - ReadWriteMany
    resources:
      requests:
        storage: ${VOLUME_CAPACITY}
    storageClassName: private

- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    name: zalenium
  spec:
    replicas: 1
    selector:
      app: zalenium
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          app: zalenium
      spec:
        containers:
        - name: zalenium
          imagePullPolicy: Always
          args:
            - "start"
            - "--desiredContainers"
            - "1"
            - "--maxDockerSeleniumContainers"
            - "1"
            - "--maxTestSessions"
            - "10"
            - "--sendAnonymousUsageInfo"
            - "false"
          env:
            - name: ZALENIUM_KUBERNETES_CPU_REQUEST
              value: "500m"
            - name: ZALENIUM_KUBERNETES_CPU_LIMIT
              value: "2"
            - name: ZALENIUM_KUBERNETES_MEMORY_REQUEST
              value: "1Gi"
            - name: ZALENIUM_KUBERNETES_MEMORY_LIMIT
              value: "4Gi"
          livenessProbe:
            failureThreshold: 2
            httpGet:
              path: /
              port: 4444
            initialDelaySeconds: 30
            periodSeconds: 60
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 4444
            initialDelaySeconds: 3
            timeoutSeconds: 10
          resources:
            requests:
              cpu: "100m"
              memory: "512M"
            limits:
              cpu: "1"
              memory: "2G"
          volumeMounts:
          - mountPath: /home/seluser/videos
            name: zalenium-videos
        serviceAccountName: zalenium
        volumes:
        - name: zalenium-videos
          persistentVolumeClaim:
            claimName: zalenium-videos
    triggers:
      - type: ConfigChange
      - imageChangeParams:
          automatic: true
          containerNames:
          - zalenium
          from:
            kind: ImageStreamTag
            name: zalenium:latest
            namespace: private
        type: ImageChange

- kind: Service
  apiVersion: v1
  metadata:
    name: zalenium
  spec:
    selector:
      app: zalenium
    ports:
    - name: zalenium
      protocol: TCP
      port: 4444
      targetPort: 4444

- kind: RoleBinding
  apiVersion: v1
  groupNames: null
  metadata:
    name: zalenium_edit
  roleRef:
    name: edit
  subjects:
  - kind: ServiceAccount
    name: zalenium
    namespace: private
```

## Expected behavior

It should just launch normally without failing.

## Test script reproducing this issue (when applicable)

```
oc create sa zalenium
oc process -f zalenium.yml | oc apply -f -
```

## Environment

OS: Linux on OpenShift
Zalenium Image Version(s): 3.141.59x
Docker version: Unknown
Docker-Compose version (if applicable): N/A
Exact Docker command to start the containers (if using docker-compose, provide 
the docker-compose file as well): N/A
If using Kubernetes, specify your environment, and if relevant your manifests: OpenShift 3.11.

**Comment by xMutaGenx** [comment]
Experiencing the same issues here

**Comment by lcharlois-neotys** [comment]
Hi,

We are experiencing the same issue since the last release too.

`line 234: /tmp/mounted/519102bd-2222-4097-aea3-73749d02fdbc/var/log/cont/firefox_browser.log: No such file or directory`

Regards,
Laurent.

**Comment by Imroath** [comment]
The same issue here

**Comment by smoke** [comment]
I confirm switching back to 3.141.59w works for me. In this version the LOGS_DIR=/var/log/cont and I suspect in 3.141.59x it is somehow wrongly set so the path ends to /tmp/mounted/37bb18a7-fa23-4e5f-8384-01a0983732c1/var/log/cont/

**Comment by anhdle14** [comment]
Experiences the same thing on GKE too.

**Comment by niranjanchintu** [comment]
Experiencing the same issue on GKE.

/usr/bin/entry.sh: line 234: /tmp/mounted/ecaf92e4-1822-4086-a58a-bf22ef24b49f/var/log/cont/firefox_browser.log: No such file or directory

**Comment by alfonso-presa** [comment]
I think it's because of the hub trying to use the videos mount to copy the videos and logs instead of api calls (because of a change I did to improve artifacts copy performance by using a shared volume, sorry guys). I'll try to check and PR with a fix ASAP. Can anyone check if removing the videos mount solves the issue? Also adding a data persistent volume along side with the videos one might solve the issue as well.

**Comment by alfonso-presa** [comment]
Fix on it's way. Even though, I recommend you all using k8s in any of it's implementations to add a `ReadWriteMany` volume claim to zalenium-data volume, as it will be used to perform the artifact copy (videos and logs) to the hub instead of using API calls to the controller. This would improve performance and scalability of the cluster and is also less error prone.

**Comment by xMutaGenx** [comment]
@alfonso-presa we currently use ReadWriteOnce for the access mode, is that what's causing us the issues then?

**Comment by alfonso-presa** [comment]
@xMutaGenx I meant `ReadWriteMany`, only for the `zalenium-data` volume. By default that volume users an `emptyDir`, but I recommend using a Claim for something like an NFS as if provided, that volume would be used for coping artifacts from browser Pods to the hub, which is way more efficient than the default behaviour that is reading a stream from the k8s api after running a tgz command in the browser pod from the hub.

**Comment by nsmandal** [comment]
Hello,
We are facing the issue with Kubernetes and our cloud solution doesn't support ReadWriteMany

We have currently
  accessModes:
    - ReadWriteOnce

The error we are noticing:
--LOG 20:54:46:861142461 Kubernetes service account found.
--LOG 20:54:46:939797681 Stopping supervisord to support docker restart...
-- INFO: Docker Img. Version: 3.141.59-333
-- INFO: Chrome..... Version: 79.0.3945.130
-- INFO: Firefox.... Version: 72.0.2
-- INFO: Using Selenium.....: 3.141.59
/usr/bin/entry.sh: line 234: /var/run/secrets/kubernetes.io/serviceaccount/2d602273-a722-4794-9765-e9523773a2f2/var/log/cont/firefox_browser.log: No such file or directory

Can you please help us. For now we have changed the docker image to 3.141.59w and works fins.

**Comment by diemol** [comment]
Merging #1136 and releasing this soon

**Comment by diemol** [comment]
Closed via #1136 
@nsmandal the solution in your case would be to stick with 3.141.59w and wait for your provider to support `ReadWriteMany`

**Comment by ceastman-ibm** [comment]
@diemol I just tried upgrading to 3.141.59z, i am getting the same error as reported by OP. My k8s persistent volumes have always been setup as ReadWriteMany

**Comment by qalinn** [comment]
Hello,
@diemol  I have the latest version and this issue is still happening.
Do you have any suggestion ?

**Comment by qalinn** [comment]
@diemol I have tried with 3.141.59w version and is working also is working with the latest version on minikube but on my k8s cluster it doesn't work.

**Comment by diemol** [comment]
I would suggest contacting your cluster admin, probably they can help to debug the issue.

**Comment by rakeshnambiar** [comment]
@diemol it's not working for me with persistent volume and the error is the same. U tried with the latest version.

```
--LOG 10:27:49:970742642 Kubernetes service account found.
--LOG 10:27:50:168202130 Stopping supervisord to support docker restart...
-- INFO: Docker Img. Version: 3.141.59-357
-- INFO: Chrome..... Version: 91.0.4472.77
-- INFO: Firefox.... Version: 88.0.1
-- INFO: Using Selenium.....: 3.141.59
/usr/bin/entry.sh: line 234: /tmp/mounted/3e1631c1-4938-4add-919c-9c179d165514/var/log/cont/firefox_browser.log: No such file or directory
```

However, when I try without the persistent disk it's all working on the same k8s cluster and I am not using Minikube.

```
persistence:
  data:
    accessMode: ReadWriteOnce
    enabled: false
    name: null
    size: 5Gi
    useExisting: true
  video:
    accessMode: ReadWriteOnce
    enabled: false
    folder: ""
    name: null
    size: 30Gi
    useExisting: false
```
