### ISSUE TITLE
Pod Error with latest docker image

### ISSUE THREAD

**Issue by ramazan0990** [zalando/zalenium#1147]
## 🐛 Bug Report

A clear and concise description of what the bug is:

Hello,
Our Zalenium deployments with the "latest" tag (dosel/zalenium:3.141.59y) makes the pods get an "Error" state. Things work just fine with "dosel/zalenium:3.141.59w" tag.

## Expected behavior

It is expected that the pods to start normally

## Environment

OS: centos 7
Zalenium Image Version(s): dosel/zalenium:3.141.59w
Docker version: 18.09.7

If using Kubernetes, specify your environment, and if relevant your manifests:
kubectl apply -f zalenium.yaml -n zalenium

```
        resources:
          limits:
            cpu: "1500m"
            memory: "4Gi"
          requests:
            cpu: "1000m"
            memory: "3Gi"
```
```
env:
        - name: MAX_DOCKER_SELENIUM_CONTAINERS
          value: "30"
        - name: DESIRED_CONTAINERS
          value: "15"
        - name: SCREEN_WIDTH
          value: "1920"
        - name: SCREEN_HEIGHT
          value: "1080"
        - name: MAX_TEST_SESSIONS
          value: "8"
        - name: TZ
          value: "Europe/Istanbul"
        - name: SELENUM_IMAGE_NAME
          value: "elgalu/selenium:latest"
        - name: ZALENIUM_KUBERNETES_CPU_REQUEST
          value: "2000m"
        - name: ZALENIUM_KUBERNETES_CPU_LIMIT
          value: "2500m"
        - name: ZALENIUM_KUBERNETES_MEMORY_REQUEST
          value: "1500Mi"
        - name: ZALENIUM_KUBERNETES_MEMORY_LIMIT
          value: "2Gi"

```

log : 
`kubectl logs -n zalenium -f zalenium-40000-zcqxh
--LOG 15:37:35:242918159 Kubernetes service account found.
--LOG 15:37:35:386548362 Stopping supervisord to support docker restart...
-- INFO: Docker Img. Version: 3.141.59-333
-- INFO: Chrome..... Version: 79.0.3945.130
-- INFO: Firefox.... Version: 72.0.2
-- INFO: Using Selenium.....: 3.141.59
/usr/bin/entry.sh: line 234: /var/run/secrets/kubernetes.io/serviceaccount/b4564cdc-3b0a-4dc9-9d11-001c2dbb127d/var/log/cont/firefox_browser.log: No such file or directory`
