### ISSUE TITLE
Location of Downloads? 

### ISSUE THREAD

**Issue by Ammadkhalid** [zalando/zalenium#1174]
When i try to download through VNC. it downloaded but i can't see it anywhere inside of docker node?

here is my docker-compose.yml:
```
chrome:
    image: "dosel/zalenium:latest"
    volumes:
      - ./media/bot/chrome-sessions/recordings:/home/seluser/videos
      - /var/run/docker.sock:/var/run/docker.sock
      - ./static:/code/static/
      - ./media:/code/media/
    command: ['start', '--timeZone', "America/Los_Angeles", '--videoRecordingEnabled', 'true', '--sauceLabsEnabled', 'false', '--browserStackEnabled', 'false', '--testingBotEnabled', 'false', '--cbtEnabled', 'false', '--startTunnel', 'false', '--lambdaTestEnabled', 'false', '--logJson', 'true']
    ports:
      - 4444:4444
```

![image](https://user-images.githubusercontent.com/14825937/78518317-9a62db80-77d9-11ea-98d9-ac90e15e5744.png)
![image](https://user-images.githubusercontent.com/14825937/78518349-ad75ab80-77d9-11ea-9d48-690de000982d.png)

but there is nothing at `/home/seluser/Downloads/` not even `Downloads`. I create it manually to see if it may work. Permission Issue?
