### ISSUE TITLE
Kubernetes - Selenium Pod Scaling

### ISSUE THREAD

**Issue by terrafying** [zalando/zalenium#1194]
## No autoscaling
If I'm reading the docs right, the argument MAX_DOCKER_SELENIUM_CONTAINERS should mean that the zalenium hub can create up to that many pods.  However, the behavior I'm observing is that it only deletes/recreates up to the same number of DESIRED_CONTAINERS, even when selenium tests are run with parallelism of 10.  Am I just doing something wrong?

## Setup
Installed zalenium chart using Helm.
Set args: 
```
hub:
      maxTestSessions: 1 # One session per container
      desiredContainers: 2 # Start out with 2 containers
      maxDockerSeleniumContainers: 20
```
This results in a zalenium pod with 
```
env:
  - name: MAX_DOCKER_SELENIUM_CONTAINERS
    value: "20"
```
