### ISSUE TITLE
kubernetes conflicts with enabling saucelabs

### ISSUE THREAD

**Issue by allandegnan** [zalando/zalenium#221]
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: zalenium
  generateName: zalenium
  labels:
    app: zalenium
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: zalenium
    spec:
      serviceAccount: zalenium
      containers:
      - name: zalenium
        image: dosel/zalenium
        securityContext:
          privileged: true
        args:
        - start
        - '--chromeContainers'
        - '1'
        - '--firefoxContainers'
        - '1'
        - '--screenWidth'
        - '1440'
        - '--screenHeight'
        - '810'
        - '--timeZone'
        - Australia/Canberra
        - '--seleniumImageName'
        - 'elgalu/selenium:latest'
        - '--sauceLabsEnabled'
        - 'true'
        ports:
        - containerPort: 4444
          protocol: TCP
        env:
        - name: ZALENIUM_KUBERNETES_CPU_REQUEST
          value: 250m
        - name: ZALENIUM_KUBERNETES_CPU_LIMIT
          value: 500m
        - name: ZALENIUM_KUBERNETES_MEMORY_REQUEST
          value: 1Gi
        - name: SAUCE_USERNAME
          value: <snip>
        - name: SAUCE_ACCESS_KEY
          value: <snip>
        volumeMounts:
        - name: zalenium-videos
          mountPath: /home/seluser/videos
        - name: zalenium-shared
          mountPath: /tmp/mounted
        - name: dockersocket
          mountPath: /var/run/docker.sock
      volumes:
      - name: zalenium-videos
        persistentVolumeClaim:
          claimName: zalenium-video
      - name: zalenium-shared
        persistentVolumeClaim:
          claimName: zalenium-nfs-pvc
      - name: dockersocket
        hostPath:
          path: /var/run/docker.sock
---
apiVersion: v1
kind: Service
metadata:
  name: zalenium
spec:
  ports:
    - name: zalenium
      port: 4444
      targetPort: 4444
  selector:
    app: zalenium
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zalenium-video
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
```

The zalenium container works and starts it's slaves with saucelabs disabled, but turning it on results in the container crashing after 40s.  Seems to be checking the docker.sock for a container called zalenium and gives an error when it never appears:

```
Error: No such container: zalenium
Error: No such container: zalenium
Error: No such container: zalenium
Error: No such container: zalenium
Error: No such container: zalenium
Error: No such container: zalenium
Error: No such container: zalenium
Error: No such container: zalenium
Error: No such container: zalenium
Error: No such container: zalenium
......................................................................................................................................................................................SauceLabsRemoteProxy failed to start after 40 seconds, failing...
```

Also getting failure earlier in startup if you don't give access to the docker.sock directly, which seems like the wrong pattern when using kubernetes.
