### ISSUE TITLE
[feature] Auto-cleanup the dashboard

### ISSUE THREAD

**Issue by simplyageek** [zalando/zalenium#274]
It'd be nice to have a custom timer (on front end) or a cronjob in the docker container which would clean up the old tests from the dashboard (older than a custom value).
Ofter I forget about hitting that "Cleanup" button and I get to the point where the disk space on my VM is an issue. I can get around that by adding a build step to my "Zalenium restart" Jenkins job, which would run a "rm -rf /tmp/videos" bash script or something similar, but it'd be nice to have it in the app.

**Comment by diemol** [comment]
Hi @simplyageek,

It sounds like something helpful, but to be honest, we don't have the capacity to implement that right now (I'm not sure when).

I suggest that you try to build your own image and add the cronjob to delete the video folder. If it works well, you could contribute back and we can put it in the Zalenium image. 

Do you think that you can help us with a PR for this?

**Comment by simplyageek** [comment]
I'll try. 😄

**Comment by diemol** [comment]
Nice, let us know how it goes!

**Comment by peerster** [comment]
Actually, I would advice __not__ to implement this in the zalenium container, since the zalenium container (in my opinion) is running enough processes already.

In openshift/k8s you can leverage the `CronJob` that will do that for you, without coupling it within the zalenium.

This is how we I do it:
```
  # Create cronjob to cleanup videos and logs
  - apiVersion: batch/v2alpha1
    kind: CronJob
    metadata:
      name: ${NAME}
    spec:
      successfulJobsHistoryLimit: 3
      failedJobsHistoryLimit: 1
      schedule: "* 23 * * *"
      jobTemplate:
        spec:
          template:
            metadata:
              labels:
                parent: ${NAME}-cronjobs
            spec:
              containers:
              - name: ${NAME}-cleaner-pod
                image: byrnedo/alpine-curl
                command: ["curl", "http://example.com/dashboard/cleanup?action=doCleanupAll"]
              restartPolicy: Never
```
