### ISSUE TITLE
Video recording is not working

### ISSUE THREAD

**Issue by mehrdad-abdoli** [zalando/zalenium#346]
Zalenium Image Version(s):  
latest: 3.7.1g
Docker Version:  
 17.09.0-ce, build afdb6d4
If using docker-compose, version:  
1.17.1, build 6d101fb
OS: 
ubuntu 14
Docker Command to start Zalenium:  
docker-compose up --force-recreate

## Expected Behavior -
video recording saved in /tmp/videos and be shown in dashboard
## Actual Behavior -
only log fiiles are in /tmp/videos/logs

here is docker-compose.yaml:

```
version: '2.2'

services:
  zalenium:
    image: "dosel/zalenium"
    container_name: zalenium
    hostname: zalenium
    tty: true
    privileged: true
    volumes:
      - /tmp/videos:/home/seluser/videos
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
    ports:
      - 8899:4444
    command: >
      start --desiredContainers 10
            --maxTestSessions 2
            --maxDockerSeleniumContainers 10
            --screenWidth 1920
            --screenHeight 1080
            --videoRecordingEnabled true
            --sauceLabsEnabled false
            --browserStackEnabled false
            --testingBotEnabled false
            --startTunnel false
    environment:
      - HOST_UID
      - HOST_GID
      - SAUCE_USERNAME
      - SAUCE_ACCESS_KEY
      - BROWSER_STACK_USER
      - BROWSER_STACK_KEY
      - TESTINGBOT_KEY
      - TESTINGBOT_SECRET
      - GRID_BROWSER_TIMEOUT=60
      - GRID_TIMEOUT=60
      - SE_OPTS=-browserTimeout 60 -timeout 60
      - zalenium_no_proxy=172.16/12, 10.0.0.0/8, *.local, 169.254/16, 192.168.99.*, localhost, 127.0.0.1
```
