### ISSUE TITLE
adding zalenium_http_proxy does not send proxy information to spawned instances

### ISSUE THREAD

**Issue by mickfeech** [zalando/zalenium#438]
Zalenium Image Version(s):  latest
Docker Version:  1.12.6
OS: RHEL7
Docker Command to start Zalenium: 
`/home/seluser/zalenium.sh start--desiredContainers10--maxTestSessions1--screenWidth1440--screenHeight810--videoRecordingEnabledfalse--seleniumImageName elgalu/selenium:latest`

Kubernetes Deployment:
```
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: '19'
  generation: 19
  labels:
    app: zalenium
    role: grid
  name: zalenium
  namespace: z2
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: zalenium
      role: grid
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: zalenium
        role: grid
    spec:
      containers:
        - args:
            - start
            - '--desiredContainers'
            - '10'
            - '--maxTestSessions'
            - '1'
            - '--screenWidth'
            - '1440'
            - '--screenHeight'
            - '810'
            - '--videoRecordingEnabled'
            - 'false'
            - '--seleniumImageName'
            - 'elgalu/selenium:latest'
          env:
            - name: https_proxy
              value: 'http://proxy.com:80'
            - name: http_proxy
              value: 'http://proxy.com:80'
            - name: no_proxy
              value: >-
                localhost,127.0.0.1,10.82.68.52,192.168.99.102, svc.cluster.local,cluster.local,.svc.cluster.local
            - name: OVERRIDE_WAIT_TIME
              value: 5m
            - name: ZALENIUM_HTTP_PROXY
              value: 'http://proxy.com:80'
            - name: ZALENIUM_HTTPS_PROXY
              value: 'http://proxy.com:80'
            - name: ZALENIUM_NO_PROXY
              value: >-
                localhost,127.0.0.1,10.82.68.52,192.168.99.102, svc.cluster.local,cluster.local,.svc.cluster.local
            - name: SEND_ANONYMOUS_USAGE_INFO
              value: 'false'
          image: dosel/zalenium
          imagePullPolicy: IfNotPresent
          name: zalenium
          ports:
            - containerPort: 4444
              protocol: TCP
          resources:
            requests:
              cpu: 250m
              memory: 400Mi
          securityContext:
            privileged: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /home/seluser/videos
              name: zalenium-data
            - mountPath: /tmp/mounted
              name: zalenium-mounted
      dnsPolicy: ClusterFirst
      hostAliases:
        - hostnames:
            - foo.local
            - bar.local
          ip: 127.0.0.1
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: zalenium
      serviceAccountName: zalenium
      terminationGracePeriodSeconds: 30
      volumes:
        - emptyDir: {}
          name: zalenium-data
        - emptyDir: {}
          name: zalenium-mounted
```

## Expected Behavior -
In spawned instances `env|grep http_proxy` to be set
## Actual Behavior -
`env|grep http_proxy` not set.
