### ISSUE TITLE
Pod creation flood when running on k8s

### ISSUE THREAD

**Issue by Vlaaaaaaad** [zalando/zalenium#441]
Issue created after discussion on [Slack](https://seleniumhq.slack.com/archives/C99KY79EK/p1518689803000467) and Gitter.

### Expected Behavior

When running a Selenium test on Kubernetes that requests 300 instances of Firefox( several scenarios running in parallel), I expected 300 pods to be created to serve that.

### Actual Behavior

Significantly more pods are are created to serve the request. The `maxDockerSeleniumContainers` limit was set to 600 and it was hit( the limit seemed to work and Zalenium reported stopping the requests due to the limit).

The following message can be seen in the logs for Zalenium hub:
```
INFO - [DS] Request has waited 30 attempts for a node, something went wrong with the previous attempts, creating a new node for { ... }
```

### Investigation and write-up

Zalenium is very... eager to schedule pods. When running a test that requests 10 pods, k8s would schedule 4, have no more space, cluster-autoscaler would create a new node that would join the cluster in a couple minutes and then the 6 pending pods would be scheduled. Meanwhile Zalenium would keep requesting new 6 pods over and over again. This leads to 20-something pods for a test that requested 10.

To confirm this an over-powered cluster was created where there were no issues with the 10-pod scheduling and subsequent cleanup. There were 10 pods requested, 10 were created, tests ran, pods were deleted. Perfect.

The same problem comes back when requesting more pods. At 300 pods, even on a larger cluster, scheduling and launching all the pods takes a while and Zalenium keeps requesting pods. For a request of 300 pods, Zalenium tries to create more than 600 pods. 

Looking a bit into the code points to this being hardcoded at
https://github.com/zalando/zalenium/blob/09f22a4375fd3f567303ec2017be7f31ba58bede/src/main/java/de/zalando/ep/zalenium/proxy/DockerSeleniumStarterRemoteProxy.java#L374 

I see no way to increase a timeout or the 30 attempts value. Something like "_OK Zalenium, you requested pods, just wait like 2 minutes for them to be ready_" would be a great addition.

### Env
**Zalenium Image Version**: 3

**Kubernetes Version**: 1.8.6, cluster created by kops, running on AWS

**Command to start Zalenium**:  installed on the cluster by deploying the helm chart with the following `values.yaml`:
```
hub:
  ## The repository and image
  ## ref: https://hub.docker.com/r/selenium/hub/
  image: "dosel/zalenium"

  ## The tag for the image
  ## ref: https://hub.docker.com/r/selenium/hub/tags/
  tag: "3"

  ## Specify a imagePullPolicy
  ## ref: http://kubernetes.io/docs/user-guide/images/#pre-pulling-images
  pullPolicy: "IfNotPresent"

  ## The port which the hub listens on
  port: 4444

  ## Timeout for probe Hub readiness via HTTP request on Hub console
  readinessTimeout: 10000

  ## Set the JAVA_OPTS environment variable
  ## If you find your selenium hub is OOMKilled, try adding -XX:+UseSerialGC
  javaOpts: "-Xmx18096m -XX:+UseSerialGC"

  ## Set the SE_OPTS environment variable
  ## ref: http://www.seleniumhq.org/docs/07_selenium_grid.jsp#node-configuration
  # seOpts:

  ## Defining a JMX port will open the port on the container, however, it
  ## requires additional javaOpts, ie
  ## javaOpts: >
  ##   -Dcom.sun.management.jmxremote.port=4000
  ##   -Dcom.sun.management.jmxremote.authenticate=false
  ##   -Dcom.sun.management.jmxremote.ssl=false
  ## ref: http://openjdk.java.net/groups/jmx/
  # jmxPort: 4000

  ## Use persistent storage or local?
  persistentVolumesEnabled: false
  localVolumesRoot: '/tmp'

  ## Configure resource requests and limits
  ## ref: http://kubernetes.io/docs/user-guide/compute-resources/
  resources:
    limits:
      cpu: "20"
      memory: "48Gi"

  ## The type of service to create
  ##   Values: ClusterIP, NodePort, LoadBalancer, or ExternalName
  ## ref: https://kubernetes.io/docs/user-guide/services/
  serviceType: "NodePort"

  ## Control where client requests go, to the same pod or round-robin
  ##   Values: ClientIP or None
  ## ref: https://kubernetes.io/docs/user-guide/services/
  serviceSessionAffinity: "None"

  # Zalenium hub uses these values to schedule pods through the k8s apiserver.
  cpuRequest: 500m
  cpuLimit: 1000m
  memRequest: 500Mi

  ## Start arguments for Zalenium hub itself
  ## https://github.com/zalando/zalenium/blob/master/docs/usage_examples.md
  desiredContainers: 2
  maxDockerSeleniumContainers: 600
  sauceLabsEnabled: false
  browserStackEnabled: false
  testingBotEnabled: false
  videoRecordingEnabled: true
  cpuRequest: 500m
  cpuLimit: 1000m
  memRequest: 500Mi
  screenWidth: 1440
  screenHeight: 900
  timeZone: "UTC"
  seleniumImageName: "elgalu/selenium"
  maxTestSessions: 5

  # Environment variables passed to Zalenium hub.
  sauceUserName: blank
  sauceAccessKey: blank
  browserStackUser: blank
  browserStackKey: blank
  testingBotKey: blank
  testingBotSecret: blank
```
