### ISSUE TITLE
Question: Shared volume

### ISSUE THREAD

**Issue by peerster** [zalando/zalenium#444]
Zalenium Image Version(s):  
3.9.1
Docker Version:  
Running in openshift origin 3.7
Docker Command to start Zalenium:  

If using Kubernetes, specify your environment, and if relevant your manifests:  
```
containers:
- args:
    - start
    - '--firefoxContainers'
    - '0'
    - '--chromeContainers'
    - '0'
    - '--seleniumImageName'
    - 'elgalu/selenium:${SELENIUM_VERSION}'
    - '--maxDockerSeleniumContainers'
    - '10'
    - '--sauceLabsEnabled'
    - 'false'
    - '--startTunnel'
    - 'false'
  env:
    - name: ZALENIUM_KUBERNETES_CPU_REQUEST
      value: 1000m
    - name: ZALENIUM_KUBERNETES_CPU_LIMIT
      value: 2000m
    - name: ZALENIUM_KUBERNETES_MEMORY_REQUEST
      value: 2Gi
    - name: SAUCE_USERNAME
      value: sauce_username
    - name: SAUCE_ACCESS_KEY
      value: sauce_access_key
    - name: GRID_BROWSER_TIMEOUT
      value: '180000'
    - name: GRID_TIMEOUT
      value: '180000'
    - name: DBUS_SESSION_BUS_ADDRESS #Don't know if this one is used
      value: /dev/null
  image: dosel/zalenium:${SELENIUM_VERSION}${ZALENIUM_PATCH_VERSION}
  imagePullPolicy: Always
  name: zalenium
  ports:
    - containerPort: 4444
      protocol: TCP
  resources:
    requests:
      cpu: '1'
      memory: 2Gi
  volumeMounts:
      - mountPath: /home/seluser/videos
        name: zalenium-videos
      - mountPath: /tmp/mounted
        name: zalenium-shared
```

## Expected Behavior -
Files being created in /tmp/mounted

## Actual Behavior -
Nothing is written (as far as I can see) to /tmp/mounted.

So my question is what the shared volume (See "Auto-mounting the shared folder" in https://zalando.github.io/zalenium/#usage) is actually used for?
Also, according to documentation, it's important to use access mode `ReadWriteMany`.
We are running with `ReadWriteOnce` without any issues (no extensive testing yet, but it works :)).

If you're interested I can share our openshift deployment files
