### ISSUE TITLE
Incompatibility with Drone CI

### ISSUE THREAD

**Issue by rredkovich** [zalando/zalenium#461]
Zalenium Image Version(s):  3 (3.10a ?)
Docker Version:  1.11.2-cs5
OS: Ubuntu 14.04.4 LTS (GNU/Linux 3.13.0-85-generic x86_64)
Drone CI: v0.8.4 (self hosted, Amazon EC2)

## Expected Behavior
Zalenium could be used with Drone CI

## Actual Behavior
Have encountered multiple errors during set up, resulting configuration ends with 
`/bin/sh: 3: cannot create /root/.netrc: Permission denied`

### First attempt
Tried to use docker client inside zalenium image, configuration like this
```yaml
 zalenium:
    image: dosel/zalenium:3
    volumes:
      - /tmp/drone/videos:/home/seluser/videos
      - /var/run/docker.sock:/var/run/docker.sock
```
resulting `Error response from daemon: client is newer than server (client API version: 1.24, server API version: 1.23)` investigation of which brings me to #83 with possible solutions:
- Upgrade your docker version (hard to do)
- Mount host docker client into container (described in #83 and dock docker-compose section, tried in [Second attempt](#second-attempt)
- Check what version of docker API 1.21 is and pass it as a parameter (have been dropped somewhere because docker client v1.13+ supports old APIs as well)

Last one should be achieved by passing `DOCKER_API_VERSION` env as mentioned in [docker docs](https://docs.docker.com/engine/reference/commandline/cli/) but somehow it doesn't work, container docker client still tries to use API v1.24 instead of passed 1.23. Unfortunately I was not able to figure out if this behavior introduced somewhere in shell scripts or somewhere in configuration.

Just in case the set up was
```yaml
 zalenium:
    image: dosel/zalenium:3
    environment:
      - DOCKER_API_VERSION=1.23
    volumes:
      - /tmp/drone/videos:/home/seluser/videos
      - /var/run/docker.sock:/var/run/docker.sock
```

### Second attempt
```yaml
  zalenium:
    image: dosel/zalenium:3
    environment:
      - HOST_UID
      - HOST_GID
      - SAUCE_USERNAME
      - SAUCE_ACCESS_KEY
      - BROWSER_STACK_USER
      - BROWSER_STACK_KEY
      - TESTINGBOT_KEY
      - TESTINGBOT_SECRET
    volumes:
      - /tmp/drone/videos:/home/seluser/videos
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
    commands:
      - |
        start --desiredContainers 2
              --maxDockerSeleniumContainers 8
              --screenWidth 800 --screenHeight 600
              --timeZone "Europe/Stockholm"
              --videoRecordingEnabled true
              --sauceLabsEnabled false
              --browserStackEnabled false
              --testingBotEnabled false
              --startTunnel false
```
Here tried to mount host docker client into container resulting described in beginning Permission denied error. Investigation of error brings me to drone support forum where [not-root user behavior described](https://discourse.drone.io/t/solved-bin-sh-3-cannot-create-root-netrc-permission-denied/321).

Just in case permissions set to host `/tmp/drone/videos` and `/root/.netrc`, however not sure that zalenium tries to write `/root/.netrc` on host.

Maybe @bradrydzewski could help us with investigation.
