### ISSUE TITLE
Request: Create Downloads directory in the Docker image with full permission like videos directory

### ISSUE THREAD

**Issue by vinsguru** [zalando/zalenium#531]
Hi @diemol 

First of all, thanks for the great work you guys have been doing.
I use zalenium and i love it. 

I have a simple request - is there any way for us to create 'Downloads' directory in the image itself with `Drwxrwxrwx` permission as we do for 'videos' directory. The issue is - when we use it docker compose - docker takes care of creating host directory. however, due to write permission issue - downloaded files will not be visible. However all the files under videos directory are visible as we have full permission in the image itself. 

```
version: "3"
services:
  zalenium:
    image: dosel/zalenium
    container_name: zalenium
    ports:
      - "$HUB_PORT:4444"
      - "$NODE_PORT:5555"      
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $WORKSPACE/downloads:/home/seluser/Downloads
      - $WORKSPACE/videos:/home/seluser/videos
    command: start
```
