### ISSUE TITLE
[Question] How to set sharing memory for the WebDriver docker container?

### ISSUE THREAD

**Issue by ansonliao** [zalando/zalenium#559]
In my case, I set the `shm_size` in the docker compose yaml file as below.

```yaml
version: "3"
services:
  selenium-hub:
    image: selenium/hub
    container_name: selenium-hub
    ports:
      - "4444:4444"

  chrome:
    image: selenium/node-chrome-debug
    depends_on:
      - selenium-hub
    ports:
      - 5900:5900
    environment:
      - HUB_PORT_4444_TCP_ADDR=selenium-hub
      - HUB_PORT_4444_TCP_PORT=4444
    shm_size: 2G
```

I set the `sharing memory` to `2G` for the `ChromeDriver` services in need.

From Zalenium, how can I set `sharing memory` for the `WebDriver` service of docker-compose?
