### ISSUE TITLE
Kubernetes internal kube-dns not working with zalenium latest

### ISSUE THREAD

**Issue by micheletest** [zalando/zalenium#616]
Zalenium Image Version(s):  
3.12.0c (not working)
3.11.0h (working)

If using Kubernetes, specify your environment, and if relevant your manifests:  
1.8.3
## Details - 

I have zalenium deployed to the same Kubernetes namespace as my test runner machines. With version 3.11.0h, I was able to use kube-dns which resolved my service name `zalenium`. When I tried to upgrade to 3.12.0c, this stopped working and I get an immediate connection refused within my test.

Example command that works with 3.11.0h but does not with 3.12.0c `py.test --base-url https://google.com --capability browserName chrome --capability resolution 1440x1440 --driver Remote --host USER_REDACTED:PASSWORD_REDACTED@zalenium --variables cap_chrome_iphone.json tests/test_google.py`

Service manifest: 
```yml
apiVersion: v1
kind: Service
metadata:
  name: zalenium
  namespace: ci
  labels:
    name: zalenium
    env: ci
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 4444
    - name: zalenium
      port: 4444
      targetPort: 4444
  selector:
    app: zalenium
```

## Expected Behavior -
I can use kube-dns when I upgrade.

## Actual Behavior -
I need to use public dns to reach my hub. (This seems to be resulting in connection drops/slow video uploads.)
