### ISSUE TITLE
Dashboard is not showing - k8s

### ISSUE THREAD

**Issue by dusansusic** [zalando/zalenium#631]
Zalenium Image Version(s):  
3.12e
Docker Version:  
17.3.2
OS: 
ubuntu 16.04

I found an issue here: https://github.com/zalando/zalenium/issues/353 and it aims that's solved but it's not.

When i deployed zalenium to the k8s, dashboard si not available till I log in into container:
`kubectl exec -it zalenium-799b7bff48-45ktv bash -n infra`
and execute:
`sudo cp * videos/`
it will work.

I am using k8s 1.10.3 accessing to dashboard:
`http://IP:PORT/dashboard`
or
`http://IP:PORT/dashboard/` - problem exists on both ways

```
          volumeMounts:
            - name: zalenium-data
              mountPath: /home/seluser/videos
```

Should we use `/home/seluser`, instead of `/home/seluser/videos`?

Also, Service is not accessible at: `http://IP:4444` but `http://IP:PORT`, eg. `http://IP:32152`

Service definition is identical to your:
```
apiVersion: v1
kind: Service
metadata:
  labels:
    app: zalenium
  name: zalenium
  namespace: infra
spec:
  ports:
  - name: zalenium
    port: 4444
    targetPort: 4444
  selector:
    app: zalenium
    role: grid
  type: NodePort
```

**Comment by dusansusic** [comment]
Anyone else who experience this issue with dashboard?

**Comment by pearj** [comment]
Port `4444` is the port that zalenium uses inside the container. Your nodeport is completely different, generally nodeports aren't useful for the internet anyhow. As most people would be using some sort of ingress.

On startup, it automatically tries to copy the dashboard files to the /home/seluser/videos mount.  Maybe look for copy errors on zalenium pod start, maybe you have some sort of permissions issues on your volume mount.

**Comment by dusansusic** [comment]
@pearj  Thanks for reply.

Well, ignore the parts with ports, my bad.

Volume is provisioned as EBS on AWS, I am not mounting it at all, k8s do that.
Container path is `/home/seluser/videos` and mount point on node is `/tmp/videos`.
I have permission issues:
```Kubernetes service account found.
Copying files for Dashboard...
cp: cannot create regular file '/home/seluser/videos/index.html': Permission denied
cp: cannot create directory '/home/seluser/videos/css': Permission denied
cp: cannot create directory '/home/seluser/videos/js': Permission denied
```
What I need to do to fix this? ^


also, I have RBAC enabled cluster and I created roles:
```
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: zalenium-role
rules:
- apiGroups: [""]
  resources:
    - "pods"
  verbs: ["create", "get", "list", "watch"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: zalenium-rbac
  namespace: infra
subjects:
- kind: ServiceAccount
  name: zalenium
  namespace: infra
roleRef:
  kind: ClusterRole
  name: zalenium-role
  apiGroup: rbac.authorization.k8s.io
```

then, I got this in logs:
```
Caused by: io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: DELETE at: https://kubernetes.default.svc/api/v1/namespaces/infra/pods/zalenium-40000-nkrnh. Message: Forbidden!Configured service account doesn't have access. Service account may have been revoked. pods "zalenium-40000-nkrnh" is forbidden: User "system:serviceaccount:infra:zalenium" cannot delete pods in the namespace "infra".
```

Why it needs permission to delete pods?

**Comment by dusansusic** [comment]
Created pull request https://github.com/zalando/zalenium/pull/635 for changing this.

**Comment by pearj** [comment]
How did you configure your kubernetes cluster? It sounds broken to me, something seems broken with your ebs-provisioner.  I've run an OpenShift cluster in AWS backed by EBS with each pod running without root privileges, and I've never needed to chown the volume before use.

**Comment by dusansusic** [comment]
provisioned with kops on aws, 3 masters + 3 nodes.

**Comment by pearj** [comment]
It needs to delete pods because once it has finished with a selenium container it deletes it unless you've configured it with maxTestSessions.

How home the ebs provisioner is mounting the volume at the node at `/tmp/videos` that seems strange to me. At least in my openshift all the volume mounts for a pod end up at something like `/var/lib/minishift/openshift.local.volumes/pods/f34ef828-7ec4-11e8-abf3-3a16ff45e523/volumes/...`
If it's using `/tmp/videos`, that sounds like you've hardcoded a host path and you're not using ebs at all...

**Comment by pearj** [comment]
I just left another comment on #635, I think you can just fix your problem with an [init container](https://kubernetes.io/docs/concepts/workloads/pods/init-containers/). You could even use the same zalenium image since it needs to exist anyway, but just put the `sudo chown` line as the `command: `

**Comment by dusansusic** [comment]
Okay. Then, call it OpenShift example, not k8s. They're everything but not same product. Vanila k8s obviously has different behaviour.

**Comment by pearj** [comment]
Can you show me the zalenium PVC and related PV kubernetes objects? Also the zalenium pod object.

**Comment by dusansusic** [comment]
Sure, of course. Here are some info:
```
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T20:17:28Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:05:37Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

PVC:
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zalenium-data
  namespace: infra
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 80Gi
```

PV:
```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: zalenium-data
  namespace: infra
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 80Gi
  hostPath:
    path: "/tmp/videos"
```

deployment:
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: zalenium
  namespace: infra
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: zalenium
        role: grid
    spec:
      containers:
        - name: zalenium
          image: dosel/zalenium:latest
          args:
            - start
            - '--desiredContainers'
            - '2'
            - '--screenWidth'
            - '1440'
            - '--screenHeight'
            - '810'
            - '--seleniumImageName'
            - 'elgalu/selenium'
            - '--maxTestSessions'
            - '4'
          env:
            - name: ZALENIUM_KUBERNETES_CPU_REQUEST
              value: 250m
            - name: ZALENIUM_KUBERNETES_CPU_LIMIT
              value: 500m
            - name: ZALENIUM_KUBERNETES_MEMORY_REQUEST
              value: 500Mi
            - name: ZALENIUM_KUBERNETES_MEMORY_LIMIT
              value: 1Gi
            - name: OVERRIDE_WAIT_TIME
              value: 5m
          resources:
            requests:
              cpu: 1000m
              memory: 1024Mi
          ports:
            - containerPort: 4444
              protocol: TCP
          volumeMounts:
            - name: zalenium-data
              mountPath: /home/seluser/videos
      volumes:
          - name: zalenium-data
            persistentVolumeClaim:
              claimName: zalenium-data
      serviceAccountName: zalenium
```


$ `kubectl get pv,pvc -n infra | grep zalenium`
```
persistentvolume/pvc-74925eb4-7e9f-11e8-b795-0a05c6d3a70a   80Gi       RWO            Delete           Bound       infra/zalenium-data                           gp2                      20h

persistentvolume/zalenium-data                              80Gi       RWO            Retain           Available                                                                          20h
persistentvolumeclaim/zalenium-data                           Bound     pvc-74925eb4-7e9f-11e8-b795-0a05c6d3a70a   80Gi       RWO            gp2            20h
```
ClusterRole and ClusterRoleBinding:
```
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: zalenium-role
rules:
- apiGroups: [""]
  resources:
    - "pods"
  verbs: ["create", "get", "list", "watch", "delete"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: zalenium-rbac
  namespace: infra
subjects:
- kind: ServiceAccount
  name: zalenium
  namespace: infra
roleRef:
  kind: ClusterRole
  name: zalenium-role
  apiGroup: rbac.authorization.k8s.io
```

$ `kubectl get po -n infra  | grep zalenium`
```
zalenium-40000-cmvl8                          1/1       Running   0          20h
zalenium-40000-j9g57                          1/1       Running   0          20h
zalenium-799b7bff48-9x8ps                     1/1       Running   0          20h
```

$ `kubectl describe pod zalenium-799b7bff48-9x8ps -n infra`
```
Name:           zalenium-799b7bff48-9x8ps
Namespace:      infra
Node:           masked_node_ip
Start Time:     Tue, 03 Jul 2018 11:11:58 +0200
Labels:         app=zalenium
                pod-template-hash=3556369904
                role=grid
Annotations:    <none>
Status:         Running
IP:             100.96.7.42
Controlled By:  ReplicaSet/zalenium-799b7bff48
Containers:
  zalenium:
    Container ID:  docker://88100ffb68e1086567e74a0519b6ce6b73b9e26c823586535bab2f58634a672e
    Image:         dosel/zalenium:latest
    Image ID:      docker-pullable://dosel/zalenium@sha256:02d30afcf3ab0a474039a230b79e03bdad48553ceb0ef98ce9ca53548164f952
    Port:          4444/TCP
    Host Port:     0/TCP
    Args:
      start
      --desiredContainers
      2
      --screenWidth
      1440
      --screenHeight
      810
      --seleniumImageName
      elgalu/selenium
      --maxTestSessions
      4
    State:          Running
      Started:      Tue, 03 Jul 2018 11:12:01 +0200
    Ready:          True
    Restart Count:  0
    Requests:
      cpu:     1
      memory:  1Gi
    Environment:
      ZALENIUM_KUBERNETES_CPU_REQUEST:     250m
      ZALENIUM_KUBERNETES_CPU_LIMIT:       500m
      ZALENIUM_KUBERNETES_MEMORY_REQUEST:  500Mi
      ZALENIUM_KUBERNETES_MEMORY_LIMIT:    1Gi
      OVERRIDE_WAIT_TIME:                  5m
    Mounts:
      /home/seluser/videos from zalenium-data (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from zalenium-token-gm2rx (ro)
Conditions:
  Type           Status
  Initialized    True 
  Ready          True 
  PodScheduled   True 
Volumes:
  zalenium-data:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  zalenium-data
    ReadOnly:   false
  zalenium-token-gm2rx:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  zalenium-token-gm2rx
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:          <none>
```

$ `kubectl describe pod zalenium-40000-j9g57 -n infra`
```
Name:         zalenium-40000-j9g57
Namespace:    infra
Node:         masked_node_ip
Start Time:   Tue, 03 Jul 2018 11:12:03 +0200
Labels:       app=zalenium
              createdBy=zalenium
Annotations:  <none>
Status:       Running
IP:           100.96.6.60
Containers:
  selenium-node:
    Container ID:   docker://cb4292c9aed28768369d22e62cbd7d3bfe3d7878dfb8b74fb9b687a7a5c86c12
    Image:          elgalu/selenium
    Image ID:       docker-pullable://elgalu/selenium@sha256:b33d2481874eb9544e12d2c08fa4136ef0c7cd64de5e93d23428b65168bf05a9
    Port:           <none>
    Host Port:      <none>
    State:          Running
      Started:      Tue, 03 Jul 2018 11:12:05 +0200
    Ready:          True
    Restart Count:  0
    Limits:
      cpu:     500m
      memory:  1Gi
    Requests:
      cpu:      250m
      memory:   500Mi
    Readiness:  exec [/bin/sh -c curl -s http://`getent hosts ${HOSTNAME} | awk '{ print $1 }'`:40000/wd/hub/status | jq .value.ready | grep true] delay=5s timeout=1s period=1s #success=1 #failure=60
    Environment:
      SEL_NODEPOLLING_MS:            106000
      SELENIUM_HUB_HOST:             100.96.7.42
      TZ:                            Europe/Berlin
      NOVNC_PORT:                    50000
      CHROME:                        false
      SELENIUM_MULTINODE_PORT:       40000
      WAIT_TIME_OUT_VIDEO_STOP:      20s
      FIREFOX:                       false
      SCREEN_HEIGHT:                 810
      WAIT_TIMEOUT:                  120s
      SCREEN_WIDTH:                  1440
      NOVNC:                         true
      SELENIUM_NODE_PARAMS:          
      SEND_ANONYMOUS_USAGE_INFO:     true
      GRID:                          false
      MULTINODE:                     true
      VIDEO_STOP_SLEEP_SECS:         1
      SELENIUM_NODE_REGISTER_CYCLE:  16000
      ZALENIUM:                      true
      SELENIUM_NODE_HOST:            {{CONTAINER_IP}}
      PICK_ALL_RANDOM_PORTS:         false
      BUILD_URL:                     
      VNC_PORT:                      60000
      SELENIUM_HUB_PORT:             4445
      SELENIUM_NODE_PROXY_PARAMS:    de.zalando.ep.zalenium.proxy.DockerSeleniumRemoteProxy
    Mounts:
      /dev/shm from dshm (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from zalenium-token-gm2rx (ro)
Conditions:
  Type           Status
  Initialized    True 
  Ready          True 
  PodScheduled   True 
Volumes:
  dshm:
    Type:    EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:  Memory
  zalenium-token-gm2rx:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  zalenium-token-gm2rx
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:          <none>
```
