### ISSUE TITLE
Service Account not found while deploying with zalenium helm chart.

### ISSUE THREAD

**Issue by CatCassie** [zalando/zalenium#719]
Zalenium Image Version(s):  
* Using the image with the latest tag 

OS: 
* Running kubectl on ubuntu linux

If using Kubernetes, specify your environment, and if relevant your manifests:  

PKS (Pivotal Container Service) with helm installed, so we are actually using the zalenium helm chart. 

below is the service-account.yaml file:

```
{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "zalenium.fullname" . }}
  labels:
    app: {{ template "zalenium.name" . }}
    chart: {{ template "zalenium.chart" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
{{- end -}}
```

## Expected Behavior -
Service account created.
## Actual Behavior -
Service account cannot be found.

### After some troubleshooting, we find the modification of service-account.yaml shown below will work:

```
{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "zalenium.serviceAccount" . }}
  labels:
    app: {{ template "zalenium.name" . }}
    chart: {{ template "zalenium.chart" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
{{- end -}}
```
* where {{ template "zalenium.serviceAccount" . }} is referencing the definitions created in the _helper.tpl file.

We are not sure if this is the desired solution but we want to share this.

Thank you,
