### ISSUE TITLE
k8s: tolerations specified for zalenium master pod are ignored for selenium slave pods

### ISSUE THREAD

**Issue by dkder3k** [zalando/zalenium#745]
As I understand at the moment when zalenium pod runs in kubernetes it shares its node selector to selenium podes. But if there are taints for k8s node and both node selector and tolerations are described for zalenium container in deployment.yaml then zalenium master starts without problem and selenium nodes stuck in pending status.
I suppose, selenium podes get node selector and don't get tolerations from zalenium pod and because of this can't start.

Zalenium Image Version(s):  
3
Kubernetes version:
1.12.1

I use k8s cluster consists of 1 master and 2 nodes. One node is labeled (`test=true`) and tainted(`test=true:NoSchedule`).
To deploy zalenium to k8s I use helm chart from the repo (docs/k8s/helm) and add to deployment.yaml:
```
nodeSelector:
  test: "true"
tolerations:
  - key: "test"
    operator: "Equal"
    value: "true"
    effect: "NoSchedule"
```

## Expected Behavior -
zalenium master and selenium slave pods starts on tainted node respecting tolerations

## Actual Behavior -
zalenium master pod starts on tainted node as expected and selenium slave pods stuck in pending status
