### ISSUE TITLE
randomly getting connection refused

### ISSUE THREAD

**Issue by Stqs** [zalando/zalenium#781]
Zalenium Image Version(s):  
dosel/zalenium:latest

Docker Version:  
18.06.1-ce, build e68fc7a

Kubernetes version:
v1.10.5

If using Kubernetes, specify your environment, and if relevant your manifests:  
```
kind: ServiceAccount
apiVersion: v1
metadata:
  name: zalenium
  namespace: test-factory
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: zalenium-role
rules:
  - verbs: ["create", "list", "get", "delete"]
    apiGroups: [""]
    resources: ["pods", "pods/exec"]
  - verbs: ["list", "create", "delete", "get"]
    apiGroups: [""]
    resources: ["services"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: zalenium
subjects:
- kind: ServiceAccount
  name: zalenium
  namespace: test-factory
roleRef:
  kind: ClusterRole
  name: zalenium-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: zalenium
  namespace: test-factory
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: zalenium
        role: grid
    spec:
      # Added to test manually https://github.com/zalando/zalenium/issues/246
      # hostAliases:
      # - ip: "127.0.0.1"
      #   hostnames:
      #   - "foo.local"
      #   - "bar.local"
      containers:
        - name: zalenium
          image: dosel/zalenium:latest
          args:
            - start
            - '--desiredContainers'
            - '2'
            - '--screenWidth'
            - '1440'
            - '--screenHeight'
            - '810'
            - '--seleniumImageName'
            - 'elgalu/selenium'
            - '--maxTestSessions'
            - '4'
            - '--videoRecordingEnabled'
            - 'false'
          env:
            - name: ZALENIUM_KUBERNETES_CPU_REQUEST
              value: 250m
            - name: ZALENIUM_KUBERNETES_CPU_LIMIT
              value: 500m
            - name: ZALENIUM_KUBERNETES_MEMORY_REQUEST
              value: 500Mi
            - name: ZALENIUM_KUBERNETES_MEMORY_LIMIT
              value: 1Gi
            - name: OVERRIDE_WAIT_TIME
              value: 5m
            - name: ZALENIUM_EXTRA_JVM_PARAMS  
              value: -Dwebdriver.http.factory=apache    
          resources:
            requests:
              cpu: 250m
              memory: 400Mi
          ports:
            - containerPort: 4444
              protocol: TCP
      #     volumeMounts:
      #       - name: zalenium-data
      #         mountPath: /home/seluser/videos
      #       - name: zalenium-mounted
      #         mountPath: /tmp/mounted
      # volumes:
      #     - name: zalenium-data
      #       emptyDir: {}
      #     - name: zalenium-mounted
      #       emptyDir: {}
      serviceAccountName: zalenium
      serviceAccount: zalenium
---
apiVersion: v1
kind: Service
metadata:
  name: zalenium
  namespace: test-factory
  labels:
    app: zalenium
spec:
  type: ClusterIP
  ports:
  - port: 4444
    targetPort: 4444
  selector:
    app: zalenium
```

## Expected Behavior -
Zalenium accepts connections constantly
```
# curl -v -s -o /dev/null http://zalenium.test-factory.svc.cluster.local:4444
* Rebuilt URL to: http://zalenium.test-factory.svc.cluster.local:4444/
*   Trying 10.43.129.76...
* TCP_NODELAY set
* Connected to zalenium.test-factory.svc.cluster.local (10.43.129.76) port 4444 (#0)
> GET / HTTP/1.1
> Host: zalenium.test-factory.svc.cluster.local:4444
> User-Agent: curl/7.52.1
> Accept: */*
>
< HTTP/1.1 200 OK
< Server: nginx/1.10.3 (Ubuntu)
< Date: Thu, 22 Nov 2018 17:43:26 GMT
< Content-Type: text/html;charset=utf-8
< Content-Length: 1676
< Connection: keep-alive
<
{ [1676 bytes data]
* Curl_http_done: called premature == 0
* Connection #0 to host zalenium.test-factory.svc.cluster.local left intact
```

## Actual Behavior -
I randomly get "Connection refused"
```
# curl -v -s -o /dev/null http://zalenium.test-factory.svc.cluster.local:4444
* Rebuilt URL to: http://zalenium.test-factory.svc.cluster.local:4444/
*   Trying 10.43.129.76...
* TCP_NODELAY set
* connect to 10.43.129.76 port 4444 failed: Connection refused
* Failed to connect to zalenium.test-factory.svc.cluster.local port 4444: Connection refused
* Closing connection 0
```

If i do `nmap -p 4444 zalenium.test-factory.svc.cluster.local` sometimes I can see 
```
PORT     STATE  SERVICE
4444/tcp closed krb524
```
sometimes 
```
PORT     STATE SERVICE
4444/tcp open  krb524
```

I've tried allocate more resources and still result is the same.
Folder /home/seluser/logs is empty. In nginx access.log inside zalenium I obviously can see only 200 responses. And error.log is empty.
Also I was monitoring nslookup for zalenium.test-factory.svc.cluster.local - its always the same. So seems like its not related to DNS.

What could cause that?

Thanks in advance!
