### ISSUE TITLE
Browser timout when deploying zalenium to a server

### ISSUE THREAD

**Issue by loic-lopez** [zalando/zalenium#816]
**Zalenium Image Version(s):**
latest
**Docker Version:**
Docker version 18.09.0, build 4d60db4
**docker-compose, version:**
docker-compose version 1.23.1, build b02f1306
**OS:** 
```
Distributor ID:	Debian
Description:	Debian GNU/Linux 9.6 (stretch)
Release:	9.6
Codename:	stretch
```
Docker Command to start Zalenium:  

docker-compose.yml:
```
version: "3"
services:
  zalenium:
    image: dosel/zalenium
    privileged: true
    container_name: zalenium
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/videos:/home/seluser/videos
    ports:
      - 4444:4444
    command: "start"
    networks:
      - tests

networks:
  tests:
      driver: bridge
```

## Expected Behavior -
Use a distant server to see the live preview like `http://domain.com:4444/grid/admin/live`.
See the live preview and dashboard on `http://domain.com:4444/grid/admin/live` and `http://domain.com:4444/dashboard`
 
## Actual Behavior -
Result in time out in the browser but works on the server by using cURL command:
```
$curl http://localhost:4444/grid/admin/live
<html>
    <head>
        <script src='/grid/resources/org/openqa/grid/images/jquery-3.1.1.min.js'></script>
        <script src='/grid/resources/org/openqa/grid/images/consoleservlet.js'></script>
        <link href='/grid/resources/org/openqa/grid/images/consoleservlet.css' rel='stylesheet' type='text/css' />
        <link href='/grid/resources/org/openqa/grid/images/favicon.ico' rel='icon' type='image/x-icon' />
        <meta http-equiv='refresh' content='1200' />
        <title>Live Preview</title>
        <style>
            .busy {opacity : 0.4; filter: alpha(opacity=40);}
        </style>
    </head>
    <body>
and so on...
```
