### ISSUE TITLE
Auto remove pods wrong/aborted tests in k8s

### ISSUE THREAD

**Issue by zpavlig** [zalando/zalenium#857]
## 🐛 Bug Report

Hello.

I have a lot of idle pods because of some wrong/aborted tests. Only delete manually.

## To Reproduce

deployment.yaml:

```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: zalenium
  namespace: zalenium
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: zalenium
        role: grid
    spec:
      containers:
        - name: zalenium
          image: dosel/zalenium:3.141.59e
          args:
            - start
            - --desiredContainers
            - '2'
            - '--timeZone'
            - 'Europe/Moscow'
            - '--screenWidth'
            - '1920'
            - '--screenHeight'
            - '1080'
            - '--seleniumImageName'
            - 'elgalu/selenium:3.141.59-p6'
            - '--maxDockerSeleniumContainers'
            - '10'
          ports:
            - containerPort: 4444
              protocol: TCP
...
```

## Expected behavior

By default, Zalenium allows a test to be idle up to 90 seconds. But pods not deleted after 90 seconds and more.

## Environment

OS: Centos 7
Zalenium Image Version(s): 3.141.59e
selenium image version: 3.141.59-p6
Docker version: 17.03.2-ce
kubernetes version: v1.11.2
