### ISSUE TITLE
Zalenium doesn't work below to AWS ELB

### ISSUE THREAD

**Issue by maauso** [zalando/zalenium#879]
## 🐛 Bug Report

We are running Zalenium on EKS using Helm, on EKS if you want to have a entry point outside the cluster, you should create a ELB. 

When we are using Zalenium with a ELB the VNC connection doesn't work, we think that the main problem is related with the proxy and the URL that it's giving to connect to the VNC

The error that we have is Disconnect timeout. 
![image](https://user-images.githubusercontent.com/9114848/53484952-50131500-3a85-11e9-97d9-8c23e598402d.png)

The url that it trying to use is 
http://zalenium.stg.company.cloud:4444/vnc/host/10.11.13.109/port/50000/?nginx=&path=proxy/10.11.13.109:50000/websockify&view_only=true

Everything works if we use NodePort instead of ELB, we mean if we use the Podip instead of ELB DNS,  but we think that we need a ELB in order to have a dynamic entrypoint according with the pods lifecycle.

Also, If we want to use a ingress in EKS it will be below ELB too, so the same problem appear  

## To Reproduce

Steps to reproduce the behavior (including the docker command/docker-compose/Kubernetes manifests to start Zalenium):

Create a service with the correct annotations to create a ELB above the service, using helm values file  
```yaml
  serviceType: "LoadBalancer"
  serviceAnnotations: {
    external-dns.alpha.kubernetes.io/hostname: zalenium.stg.company.cloud, 
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http,
    service.beta.kubernetes.io/aws-load-balancer-internal: "0.0.0.0/0",
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "True"
  }
```
## Expected behavior

Connect to VNC 

## Environment

OS: Amazon Linux 2
Zalenium Image Version(s):   zalenium:3
If using Kubernetes, specify your environment, and if relevant your manifests: EKS 1.11
