### ISSUE TITLE
Test-execution stopped in case of any any test failed

### ISSUE THREAD

**Issue by rakeshnambiar** [zalando/zalenium#883]
Test-execution stopped in case of any any test failed. I was using traditional Selenium-Grid in docker-compose settings and now replaced it with Zalenium and started facing this issue.

Expected behavior
It should continue the execution though any test failed in between

I can see something like in the terminal.
 WebDriverError: Reached error page: about:neterror?e=netReset

My docker-compose file looks like below
```
version: "3"
services:
    zalenium:
        image: "dosel/zalenium"
        container_name: zalenium
        hostname: zalenium
        tty: true
        restart: always
        volumes:
          #- /tmp/videos:/home/seluser/videos
          - ./script/target/:/home/seluser/videos
          - /var/run/docker.sock:/var/run/docker.sock
          - /usr/bin/docker:/usr/bin/docker
        ports:
          - 4444:4444
        command: >
           start --desiredContainers 8
                 --maxDockerSeleniumContainers 8
                 --screenWidth 1920 --screenHeight 1080
                 --timeZone "Europe/Berlin"
                 --videoRecordingEnabled true
                 --sauceLabsEnabled false
                 --browserStackEnabled false
                 --testingBotEnabled false
                 --startTunnel false
   
    nodeSetup:
        image: timbru31/java-node:8
        volumes:
          - ./script:/usr/src/script
        working_dir: /usr/src/script
        command:
          - sh
          - '-c'
          - 'npm install && npm test'
        ports:
          - 7070:7070
```
