### ISSUE TITLE
Feature: allow configuration of nodeSelector and tolerations for spawned agents

### ISSUE THREAD

**Issue by schlippi** [zalando/zalenium#942]
## 🚀 Feature Proposal

Allow the user/admin to specify the Kubernetes nodeSelector and/or tolerations which are attached to spawned agents.

## Motivation

Split run location of hub, which is a permanent service, from the agents, which are preemptible.
This would allow running hub on a nodepool with permanent nodes and the agents on an on-demand nodepool.

## Example

Example config:
```
env:
  - name: ZALENIUM_KUBERNETES_TOLERATIONS
    value: "---\n- effect: \"NoExecute\"\n  key: \"no-cluster-autoscaling\"\n  operator: \"Equal\"\n  value: \"false\"\n- effect: \"NoExecute\"\n  key: \"cluster-autoscaling\"\n  operator: \"Equal\"\n  value: \"true\""
  - name: ZALENIUM_KUBERNETES_NODE_SELECTOR
    value: "beta.kubernetes.io/arch=linux", kops.k8s.io/instancegroup=no-cluster-autoscaling"
```

would translate in PodSpec to
```
Node-Selectors:
  - beta.kubernetes.io/arch=linux
  - kops.k8s.io/instancegroup=no-cluster-autoscaling
Tolerations:
  - no-cluster-autoscaling=false:NoExecute
  - cluster-autoscaling=true:NoExecute
```
